// Хражевник — кеш-прокси и зеркало linux-репозиториев
// Copyright (C) 2026 AlexRus1234
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

package apk

import (
	"archive/tar"
	"bufio"
	"bytes"
	"compress/gzip"
	"context"
	"crypto"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha1"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"errors"
	"fmt"
	"io"
	"iter"
	"math/big"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/klauspost/compress/zstd"

	"khrazhevnik/internal/core/domain"
	"khrazhevnik/internal/core/port"
	"khrazhevnik/internal/testutil"
)

// buildApkTarGz собирает .apk (v2): gzip+tar с .PKGINFO + один data-файл.
func buildApkTarGz(t *testing.T, pkginfo string) []byte {
	t.Helper()
	return buildApkCompressed(t, pkginfo, true)
}

// buildApkTarZst собирает .apk (v3): zstd+tar с .PKGINFO.
func buildApkTarZst(t *testing.T, pkginfo string) []byte {
	t.Helper()
	return buildApkCompressed(t, pkginfo, false)
}

func buildApkCompressed(t *testing.T, pkginfo string, gzipFlag bool) []byte {
	t.Helper()
	var tarBuf bytes.Buffer
	tw := tar.NewWriter(&tarBuf)
	content := []byte(pkginfo)
	if err := tw.WriteHeader(&tar.Header{
		Name: ".PKGINFO", Typeflag: tar.TypeReg, Mode: 0o644, Size: int64(len(content)),
	}); err != nil {
		t.Fatal(err)
	}
	if _, err := tw.Write(content); err != nil {
		t.Fatal(err)
	}
	if err := tw.WriteHeader(&tar.Header{
		Name: "usr/bin/foo", Typeflag: tar.TypeReg, Mode: 0o755, Size: 0,
	}); err != nil {
		t.Fatal(err)
	}
	if err := tw.Close(); err != nil {
		t.Fatal(err)
	}
	var out bytes.Buffer
	if gzipFlag {
		gz := gzip.NewWriter(&out)
		if _, err := gz.Write(tarBuf.Bytes()); err != nil {
			t.Fatal(err)
		}
		if err := gz.Close(); err != nil {
			t.Fatal(err)
		}
	} else {
		zw, err := zstd.NewWriter(&out)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := zw.Write(tarBuf.Bytes()); err != nil {
			t.Fatal(err)
		}
		if err := zw.Close(); err != nil {
			t.Fatal(err)
		}
	}
	return out.Bytes()
}

const pkginfoText = `# Generated by abuild
pkgname = apk-example
pkgver = 1.0-r0
pkgdesc = example package
url = https://example.com
builddate = 1724323200
packager = Test Packager <test@example.com>
size = 2048
arch = x86_64
license = MIT
origin = apk-example
`

func TestParsePkgInfoGolden(t *testing.T) {
	t.Parallel()
	pi, err := ParsePkgInfo(strings.NewReader(pkginfoText))
	if err != nil {
		t.Fatalf("ParsePkgInfo: %v", err)
	}
	if pi.Name != "apk-example" {
		t.Errorf("Name = %q", pi.Name)
	}
	if pi.Version != "1.0-r0" {
		t.Errorf("Version = %q", pi.Version)
	}
	if pi.Arch != "x86_64" {
		t.Errorf("Arch = %q", pi.Arch)
	}
	if pi.Origin != "apk-example" {
		t.Errorf("Origin = %q", pi.Origin)
	}
	if pi.Size != 2048 {
		t.Errorf("Size = %d", pi.Size)
	}
}

func TestParsePkgInfoMultiLicense(t *testing.T) {
	t.Parallel()
	pi, err := ParsePkgInfo(strings.NewReader("pkgname = foo\nlicense = MIT\nlicense = BSD\n"))
	if err != nil {
		t.Fatal(err)
	}
	if len(pi.License) != 2 || pi.License[0] != "MIT" || pi.License[1] != "BSD" {
		t.Errorf("License = %+v", pi.License)
	}
}

func TestParsePkgInfoCommentsCRLF(t *testing.T) {
	t.Parallel()
	pi, err := ParsePkgInfo(strings.NewReader("# c\r\npkgname = foo\r\n\r\npkgver = 1.0-r0\r\n"))
	if err != nil {
		t.Fatal(err)
	}
	if pi.Name != "foo" || pi.Version != "1.0-r0" {
		t.Errorf("Name=%q Version=%q", pi.Name, pi.Version)
	}
}

func TestParsePkgInfoUnknownKey(t *testing.T) {
	t.Parallel()
	pi, err := ParsePkgInfo(strings.NewReader("futurefield = x\npkgname = bar\n"))
	if err != nil {
		t.Fatal(err)
	}
	if pi.Name != "bar" {
		t.Errorf("Name = %q", pi.Name)
	}
}

func TestParsePkgInfoTooLarge(t *testing.T) {
	t.Parallel()
	big := strings.Repeat("a", maxPkgInfoSize+1)
	_, err := ParsePkgInfo(strings.NewReader(big))
	if !errors.Is(err, ErrPkgInfoTooLarge) {
		t.Fatalf("ожидалась ErrPkgInfoTooLarge, получено %v", err)
	}
}

func TestReadPkgInfoFromPackageGzip(t *testing.T) {
	t.Parallel()
	apk := buildApkTarGz(t, pkginfoText)
	pi, err := readPkgInfoFromPackage(context.Background(), bytes.NewReader(apk), 0)
	if err != nil {
		t.Fatalf("readPkgInfoFromPackage gzip: %v", err)
	}
	if pi.Name != "apk-example" {
		t.Errorf("Name = %q", pi.Name)
	}
}

func TestReadPkgInfoFromPackageZstd(t *testing.T) {
	t.Parallel()
	apk := buildApkTarZst(t, pkginfoText)
	pi, err := readPkgInfoFromPackage(context.Background(), bytes.NewReader(apk), 0)
	if err != nil {
		t.Fatalf("readPkgInfoFromPackage zstd: %v", err)
	}
	if pi.Name != "apk-example" {
		t.Errorf("Name = %q", pi.Name)
	}
}

func TestReadPkgInfoFromTarMissing(t *testing.T) {
	t.Parallel()
	var tarBuf bytes.Buffer
	tw := tar.NewWriter(&tarBuf)
	_ = tw.WriteHeader(&tar.Header{Name: "usr/bin/foo", Typeflag: tar.TypeReg, Mode: 0o755, Size: 0})
	_ = tw.Close()
	_, err := readPkgInfoFromTar(context.Background(), bytes.NewReader(tarBuf.Bytes()))
	if !errors.Is(err, ErrBadApk) {
		t.Fatalf("ожидали ErrBadApk для tar без .PKGINFO, got %v", err)
	}
}

func TestGeneratorName(t *testing.T) {
	t.Parallel()
	g := &Generator{}
	if g.Name() != Name {
		t.Errorf("Name = %q, want %q", g.Name(), Name)
	}
}

// TestValidateObjectPath — пакет обязан лежать в каталоге своей
// архитектуры (сессия 192): клиент строит URL как
// <repo>/<A: записи>/<basename(F:)>, из корня репо и из вложенного
// каталога пакет недоступен.
func TestValidateObjectPath(t *testing.T) {
	t.Parallel()
	g := &Generator{}
	cases := []struct {
		path string
		want bool
	}{
		{"x86_64/apk-example-1.0-r0.apk", true},
		{"aarch64/htop-3.3.0-r2.apk", true},
		{"noarch/ca-certificates-20250605-r0.apk", true},
		{"apk-example-1.0-r0.apk", false},
		{"x86_64/sub/apk-example-1.0-r0.apk", false},
		{"apkindex.tar.gz", false},
		{"apkindex.tar.gz.sig", false},
		{"x86_64/apkindex.tar.gz", false},
		{"foo.txt", false},
		{"", false},
	}
	for _, c := range cases {
		err := g.ValidateObjectPath(c.path)
		got := err == nil
		if got != c.want {
			t.Errorf("ValidateObjectPath(%q) = %v, want ok=%v", c.path, err, c.want)
		}
	}
}

// port.FamilyResolver — compile-time контракт генератора.
var _ port.FamilyResolver = (*Generator)(nil)

// TestObjectFamily — port.FamilyResolver: семейство версий apk-объекта —
// имя пакета из basename до сегмента-версии. Реальные имена Alpine.
func TestObjectFamily(t *testing.T) {
	t.Parallel()
	g := &Generator{}
	cases := []struct {
		path   string
		family string
		ok     bool
	}{
		{"htop-3.3.0-r2.apk", "htop", true},
		{"libnl3-3.11.0-r0.apk", "libnl3", true},
		// Имя с дефисом: семейство — всё до сегмента-версии.
		{"py3-pip-25.1.1-r0.apk", "py3-pip", true},
		{"ca-certificates-20250605-r0.apk", "ca-certificates", true},
		// Пакеты могут лежать в подкаталоге — берём basename.
		{"x86_64/htop-3.3.0-r2.apk", "htop", true},
		// Имя без границы версии (мусор) — вне семейств.
		{"htop.apk", "", false},
		// Индексы, подписи и ключи — вне семейств.
		{"APKINDEX.tar.gz", "", false},
		{"APKINDEX.tar.gz.sig", "", false},
		{"khrazhevnik.rsa.pub", "", false},
		{"", "", false},
	}
	for _, c := range cases {
		family, ok := g.ObjectFamily(c.path)
		if ok != c.ok || family != c.family {
			t.Errorf("ObjectFamily(%q) = (%q, %v), want (%q, %v)", c.path, family, ok, c.family, c.ok)
		}
	}
}

// port.CacheFamilyResolver — compile-time контракт генератора кеш-путей.
var _ port.CacheFamilyResolver = (*Generator)(nil)

// TestCacheObjectFamily — port.CacheFamilyResolver: семейство версий
// объекта кеш-прокси по upstream-пути Alpine-зеркала (не путь внутри
// личного репо): пакет лежит в каталоге своей арх, семейство берётся из
// basename. Реальные имена Alpine (урок сессии 65).
func TestCacheObjectFamily(t *testing.T) {
	t.Parallel()
	g := &Generator{}
	cases := []struct {
		path   string
		family string
		ok     bool
	}{
		{"/v3.20/main/x86_64/htop-3.3.0-r2.apk", "htop", true},
		{"/v3.20/main/x86_64/libnl3-3.11.0-r0.apk", "libnl3", true},
		{"/v3.20/main/x86_64/py3-pip-25.1.1-r0.apk", "py3-pip", true},
		// Индексы, подписи и ключи — вне семейств.
		{"/v3.20/main/x86_64/APKINDEX.tar.gz", "", false},
		{"/v3.20/main/x86_64/APKINDEX.tar.gz.sig", "", false},
		{"", "", false},
	}
	for _, c := range cases {
		family, ok := g.CacheObjectFamily(c.path)
		if ok != c.ok || family != c.family {
			t.Errorf("CacheObjectFamily(%q) = (%q, %v), want (%q, %v)", c.path, family, ok, c.family, c.ok)
		}
	}
}

// putApk складывает .apk-байты в FakeStorage.
func putApk(t *testing.T, storage *testutil.FakeStorage, repo domain.Repo, name, pkginfo string) string {
	t.Helper()
	apk := buildApkTarGz(t, pkginfo)
	key := port.RepoPrefix(repo) + "/" + name
	w, err := storage.Put(context.Background(), key)
	if err != nil {
		t.Fatalf("storage.Put %s: %v", key, err)
	}
	if _, err := w.Write(apk); err != nil {
		t.Fatalf("w.Write %s: %v", key, err)
	}
	if err := w.Commit(context.Background()); err != nil {
		t.Fatalf("w.Commit %s: %v", key, err)
	}
	return key
}

func readStorage(t *testing.T, storage *testutil.FakeStorage, key string) []byte {
	t.Helper()
	obj, err := storage.Get(context.Background(), key)
	if err != nil {
		t.Fatalf("Get %s: %v", key, err)
	}
	defer obj.Body.Close()
	b, err := io.ReadAll(obj.Body)
	if err != nil {
		t.Fatalf("ReadAll %s: %v", key, err)
	}
	return b
}

func TestGenerateIndexesSingleApk(t *testing.T) {
	t.Parallel()
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/apk-example-1.0-r0.apk", pkginfoText)

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}

	// APKINDEX.tar.gz: gzip+tar с файлом APKINDEX. Разжимаем gzip → tar.
	idxGz := readStorage(t, storage, "repo/1/apk/x86_64/apkindex.tar.gz")
	gz, err := gzip.NewReader(bytes.NewReader(idxGz))
	if err != nil {
		t.Fatalf("gzip.NewReader: %v", err)
	}
	text, err := extractAPKINDEXText(gz)
	if err != nil {
		t.Fatalf("extractAPKINDEXText: %v", err)
	}
	for _, want := range []string{
		"P:apk-example\n",
		"V:1.0-r0\n",
		"A:x86_64\n",
		"T:example package\n",
		"F:x86_64/apk-example-1.0-r0.apk\n",
		"C:Q1",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("APKINDEX не содержит %q:\n%s", want, text)
		}
	}
}

// extractAPKINDEXText находит файл APKINDEX в tar-потоке и возвращает его
// текст (для проверок формата).
func extractAPKINDEXText(r io.Reader) (string, error) {
	tr := tar.NewReader(r)
	for {
		hdr, err := tr.Next()
		if err != nil {
			return "", err
		}
		base := hdr.Name
		if idx := strings.LastIndexByte(base, '/'); idx >= 0 {
			base = base[idx+1:]
		}
		if base == "APKINDEX" {
			b, _ := io.ReadAll(tr)
			return string(b), nil
		}
	}
}

// roundtrip: список .apk → APKINDEX.tar.gz → ParseAPKINDEX → те же F:.
func TestGenerateIndexesRoundtrip(t *testing.T) {
	t.Parallel()
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/apk-example-1.0-r0.apk",
		"pkgname = apk-example\npkgver = 1.0-r0\narch = x86_64\n")
	putApk(t, storage, repo, "x86_64/second-pkg-2.0-r1.apk",
		"pkgname = second-pkg\npkgver = 2.0-r1\narch = x86_64\n")

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}

	idxGz := readStorage(t, storage, "repo/1/apk/x86_64/apkindex.tar.gz")
	// ParseAPKINDEX сам разжимает gzip; передаём сырые байты.
	entries, err := collectIndex(ParseAPKINDEX(bytes.NewReader(idxGz)))
	if err != nil {
		t.Fatalf("ParseAPKINDEX roundtrip: %v", err)
	}
	paths := map[string]bool{}
	for _, e := range entries {
		paths[e.FilePath] = true
	}
	want := []string{
		"x86_64/apk-example-1.0-r0.apk",
		"x86_64/second-pkg-2.0-r1.apk",
	}
	for _, w := range want {
		if !paths[w] {
			t.Errorf("filepath %q отсутствует в APKINDEX (roundtrip): %+v", w, paths)
		}
	}
}

// TestGenerateIndexesEmptyRepo — пакетов нет, архитектур взять неоткуда:
// генератор не пишет ни одного индекса (в прежней схеме здесь появлялся
// «пустой» индекс в корне репо).
func TestGenerateIndexesEmptyRepo(t *testing.T) {
	t.Parallel()
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes пустой репо: %v", err)
	}
	for meta, err := range storage.List(context.Background(), "repo/1/apk/") {
		if err != nil {
			t.Fatalf("List: %v", err)
		}
		t.Errorf("пустой репо записал объект %q", meta.Key)
	}
}

func TestGenerateIndexesWrongEcosystem(t *testing.T) {
	t.Parallel()
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: "apt"}
	g := &Generator{}
	err := g.GenerateIndexes(context.Background(), repo, storage, nil)
	var unsup *domain.UnsupportedError
	if !errors.As(err, &unsup) {
		t.Fatalf("ожидали UnsupportedError, получили %v", err)
	}
}

func TestGenerateIndexesContextCanceled(t *testing.T) {
	t.Parallel()
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo.apk", pkginfoText)
	g := &Generator{}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if err := g.GenerateIndexes(ctx, repo, storage, nil); err == nil {
		t.Fatal("ожидали ошибку отменённого контекста")
	}
}

// recordingProgress ловит кадры Update.
type recordingProgress struct {
	updates []string
	logs    []string
}

func (r *recordingProgress) Update(phase, current string, processed, total int64) {
	r.updates = append(r.updates, fmt.Sprintf("%s/%s/%d/%d", phase, current, processed, total))
}
func (r *recordingProgress) Log(line string) { r.logs = append(r.logs, line) }

func TestGenerateIndexesProgress(t *testing.T) {
	t.Parallel()
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo.apk", pkginfoText)
	g := &Generator{}
	rec := &recordingProgress{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, rec); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}
	phases := map[string]bool{}
	for _, u := range rec.updates {
		phases[strings.SplitN(u, "/", 2)[0]] = true
	}
	for _, want := range []string{"enumerate", "pkginfo", "write"} {
		if !phases[want] {
			t.Errorf("фаза %s не отработала: %v", want, rec.updates)
		}
	}
	if !slices.ContainsFunc(rec.logs, func(s string) bool { return strings.Contains(s, "индексы записаны") }) {
		t.Errorf("нет строки завершения: %v", rec.logs)
	}
}

// testRsaSigner — port.RsaSigner поверх настоящего маленького ключа
// (1024 бита): контракт подписи индекса проверяется настоящей
// верификацией, а не маркером. mod/sign/rsasha256 тест не тянет
// (mod→mod запрещён depguard'ом), поэтому повторяет контракт сам —
// прецедент xbps gen_test.
type testRsaSigner struct {
	priv   *rsa.PrivateKey
	pubPEM []byte
}

func newTestRsaSigner(t *testing.T) *testRsaSigner {
	t.Helper()
	priv, err := rsa.GenerateKey(rand.Reader, 1024)
	if err != nil {
		t.Fatalf("rsa.GenerateKey: %v", err)
	}
	der, err := x509.MarshalPKIXPublicKey(&priv.PublicKey)
	if err != nil {
		t.Fatalf("MarshalPKIXPublicKey: %v", err)
	}
	return &testRsaSigner{
		priv:   priv,
		pubPEM: pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: der}),
	}
}

// SignSHA1DigestInfo — подпись индекса apk (сессия 195): sha1 в
// SHA-1-DigestInfo, PKCS#1 v1.5. Остальные методы интерфейса —
// заглушки: apk их не зовёт.
func (s *testRsaSigner) SignSHA1DigestInfo(_ context.Context, digest []byte) ([]byte, error) {
	if len(digest) != sha1.Size {
		return nil, fmt.Errorf("дайджест длиной %d, хочу %d", len(digest), sha1.Size)
	}
	return rsa.SignPKCS1v15(nil, s.priv, crypto.SHA1, digest)
}

func (s *testRsaSigner) SignSHA256(context.Context, []byte) ([]byte, error) {
	return nil, errors.New("apk: SignSHA256 не используется")
}

func (s *testRsaSigner) SignSHA256SHA1DigestInfo(context.Context, []byte) ([]byte, error) {
	return nil, errors.New("apk: SignSHA256SHA1DigestInfo не используется")
}

func (s *testRsaSigner) PublicKeyPEM() ([]byte, error) {
	out := make([]byte, len(s.pubPEM))
	copy(out, s.pubPEM)
	return out, nil
}

// apkSHA1DigestInfoPrefix — ожидаемая обёртка DigestInfo для SHA-1
// (OID 1.3.14.3.2.26, октет-строка 20 байт): SEQ 0x21 = algid 11 +
// заголовок октета 2 + дайджест. Байты сняты с живой подписи ИНДЕКСА
// Alpine (`openssl pkeyutl -verifyrecover` по .SIGN.RSA индекса
// edge/main/x86_64 — постамбула 195), а не выведены из stdlib: тест
// обязан падать, если формат разъедется.
var apkSHA1DigestInfoPrefix = []byte{0x30, 0x21, 0x30, 0x09, 0x06, 0x05, 0x2b, 0x0e, 0x03, 0x02, 0x1a, 0x05, 0x00, 0x04, 0x14}

// splitGzipMembers делит APKINDEX.tar.gz на gzip-члены ровно по границам
// байтов (apkByteReader — io.ByteReader, gzip.Reader не читает вперёд).
func splitGzipMembers(t *testing.T, data []byte) [][]byte {
	t.Helper()
	br := &apkByteReader{src: bytes.NewReader(data)}
	var out [][]byte
	rest := int64(len(data))
	for rest > 0 {
		start := br.n
		zr, err := gzip.NewReader(br)
		if err != nil {
			t.Fatalf("gzip.NewReader (член %d): %v", len(out), err)
		}
		zr.Multistream(false)
		if _, err := io.Copy(io.Discard, zr); err != nil {
			t.Fatalf("чтение члена %d: %v", len(out), err)
		}
		if err := zr.Close(); err != nil {
			t.Fatalf("закрытие члена %d: %v", len(out), err)
		}
		out = append(out, data[start:br.n])
		rest = int64(len(data)) - br.n
	}
	return out
}

// tarFiles возвращает имя → содержимое обычных файлов члена.
func tarFiles(t *testing.T, gzMember []byte) map[string][]byte {
	t.Helper()
	zr, err := gzip.NewReader(bytes.NewReader(gzMember))
	if err != nil {
		t.Fatalf("gzip.NewReader: %v", err)
	}
	defer zr.Close()
	tr := tar.NewReader(zr)
	out := map[string][]byte{}
	for {
		hdr, err := tr.Next()
		if errors.Is(err, io.EOF) {
			return out
		}
		if err != nil {
			t.Fatalf("tar.Next: %v", err)
		}
		b, err := io.ReadAll(tr)
		if err != nil {
			t.Fatalf("tar.ReadAll %s: %v", hdr.Name, err)
		}
		out[hdr.Name] = b
	}
}

// tarFileNames возвращает имена обычных файлов непрерывного tar-потока.
func tarFileNames(t *testing.T, rawTar []byte) []string {
	t.Helper()
	tr := tar.NewReader(bytes.NewReader(rawTar))
	var out []string
	for {
		hdr, err := tr.Next()
		if errors.Is(err, io.EOF) {
			return out
		}
		if err != nil {
			t.Fatalf("tar.Next: %v", err)
		}
		out = append(out, hdr.Name)
	}
}

// verifyRecover повторяет openssl pkeyutl -verifyrecover (сырая
// RSA-операция публичным ключом) без openssl-вызовов: sig^e mod n даёт
// EM = 0x01 | 0xFF…FF | 0x00 | DigestInfo (PKCS#1 v1.5), возвращаем
// ровно DigestInfo — паддинг проверяется по ходу, его порча тоже
// означает несовпадение.
func verifyRecover(t *testing.T, pub *rsa.PublicKey, sig []byte) []byte {
	t.Helper()
	m := new(big.Int).SetBytes(sig)
	m.Exp(m, big.NewInt(int64(pub.E)), pub.N)
	em := m.Bytes()
	idx := bytes.IndexByte(em, 0x00)
	if len(em) == 0 || em[0] != 0x01 || idx < 8 {
		t.Fatalf("EM не PKCS#1 v1.5: %x", em)
	}
	for _, b := range em[1:idx] {
		if b != 0xff {
			t.Fatalf("EM не PKCS#1 v1.5 (PS не 0xFF): %x", em)
		}
	}
	return em[idx+1:]
}

// TestGenerateIndexesUnsignedNoSig — без подписчика индекс отдаётся
// одним gzip-членом с единственным tar-членом APKINDEX: ни
// сигнатурной секции внутри, ни отдельного .sig-объекта.
func TestGenerateIndexesUnsignedNoSig(t *testing.T) {
	t.Parallel()
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo.apk", pkginfoText)
	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}
	if _, err := storage.Get(context.Background(), "repo/1/apk/x86_64/apkindex.tar.gz.sig"); err == nil {
		t.Error("создан detached apkindex.tar.gz.sig (apk его не запрашивает)")
	}
	idx := readStorage(t, storage, "repo/1/apk/x86_64/apkindex.tar.gz")
	members := splitGzipMembers(t, idx)
	if len(members) != 1 {
		t.Fatalf("неподписанный индекс = %d gzip-членов, want 1", len(members))
	}
	entries := tarFiles(t, members[0])
	if _, ok := entries["APKINDEX"]; !ok {
		t.Errorf("нет tar-члена APKINDEX: %v", entries)
	}
	for name := range entries {
		if strings.HasPrefix(name, ".SIGN.") {
			t.Errorf("неподписанный индекс содержит сигнатурную секцию: %q", name)
		}
	}
}

// TestGenerateIndexesSignedIndexSignature — контракт формата подписи
// индекса apk (сессия 195), байтовая сверка без openssl:
//  1. индекс — ровно два gzip-члена, первый tar содержит единственный
//     член `.SIGN.RSA.khrazhevnik.rsa.pub` (имя = keyid файла
//     /etc/apk/keys на клиенте);
//  2. verifyrecover публичным ключом даёт ровно SHA-1-DigestInfo +
//     sha1 СЖАТЫХ байт второго члена (тело индекса «как файл»);
//  3. тело остаётся обычным APKINDEX.tar.gz (разжимается в tar с
//     файлом APKINDEX) — подпись не ломает тело;
//  4. отдельного .sig-объекта генератор не пишет.
func TestGenerateIndexesSignedIndexSignature(t *testing.T) {
	t.Parallel()
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo.apk", pkginfoText)
	rsaSigner := newTestRsaSigner(t)
	g := &Generator{rsa: rsaSigner}
	rec := &recordingProgress{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, rec); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}

	idx := readStorage(t, storage, "repo/1/apk/x86_64/apkindex.tar.gz")
	members := splitGzipMembers(t, idx)
	if len(members) != 2 {
		t.Fatalf("подписанный индекс = %d gzip-членов, want 2", len(members))
	}
	sigEntries := tarFiles(t, members[0])
	wantName := ".SIGN.RSA." + apkKeyID
	sig, ok := sigEntries[wantName]
	if !ok || len(sigEntries) != 1 {
		t.Fatalf("первый член = %v, want единственный %q", keysOf(sigEntries), wantName)
	}
	if len(sig) != rsaSigner.priv.Size() {
		t.Errorf("длина подписи = %d, want %d (модуль ключа)", len(sig), rsaSigner.priv.Size())
	}

	// 2. verifyrecover: DigestInfo = SHA-1-обёртка + sha1(body).
	want := append(append([]byte{}, apkSHA1DigestInfoPrefix...), sha1Sum(members[1])...)
	if got := verifyRecover(t, &rsaSigner.priv.PublicKey, sig); !bytes.Equal(got, want) {
		t.Errorf("verifyrecover = %x, want %x", got, want)
	}

	// 3. Тело — обычный APKINDEX.tar.gz.
	text, err := extractAPKINDEXText(bytes.NewReader(mustGunzip(t, members[1])))
	if err != nil {
		t.Fatalf("тело индекса не разбирается: %v", err)
	}
	if !strings.Contains(text, "P:apk-example\n") {
		t.Errorf("в теле индекса нет записи пакета: %q", text)
	}

	// 3б. Склейка членов — ОДИН непрерывный tar: сигнатурная секция
	// продолжается телом. Концевые нулевые блоки в первом члене сломали бы
	// это (парсер apk/gnu tar останавливается на сигнатуре, индекс пуст),
	// поэтому проверяется не только состав члена, но и непрерывность.
	names := tarFileNames(t, mustGunzip(t, idx))
	if want := []string{".SIGN.RSA." + apkKeyID, "APKINDEX"}; !slices.Equal(names, want) {
		t.Errorf("tar через границу членов = %v, want %v", names, want)
	}

	// 4. Отдельного detached .sig нет.
	if _, err := storage.Get(context.Background(), "repo/1/apk/x86_64/apkindex.tar.gz.sig"); err == nil {
		t.Error("создан detached apkindex.tar.gz.sig (apk его не запрашивает)")
	}

	phases := map[string]bool{}
	for _, u := range rec.updates {
		phases[strings.SplitN(u, "/", 2)[0]] = true
	}
	if !phases["sign"] {
		t.Errorf("фаза sign не отработала: %v", rec.updates)
	}
}

// TestGenerateIndexesSignedTamperedBodyFailsVerification — страховка
// контракта: подпись накрывает именно тело индекса, поэтому порча
// байта тела ломает сверку (иначе тест 2 доказывал бы не то).
func TestGenerateIndexesSignedTamperedBodyFailsVerification(t *testing.T) {
	t.Parallel()
	signer := newTestRsaSigner(t)
	body, err := buildAPKINDEXTarGz([]byte("P:foo\nV:1.0-r0\n\n"))
	if err != nil {
		t.Fatalf("buildAPKINDEXTarGz: %v", err)
	}
	sig, err := signer.SignSHA1DigestInfo(context.Background(), sha1Sum(body))
	if err != nil {
		t.Fatalf("SignSHA1DigestInfo: %v", err)
	}
	tampered := append([]byte{}, body...)
	tampered[len(tampered)/2] ^= 0xff
	got := verifyRecover(t, &signer.priv.PublicKey, sig)
	want := append(append([]byte{}, apkSHA1DigestInfoPrefix...), sha1Sum(tampered)...)
	if bytes.Equal(got, want) {
		t.Error("подпись сошлась на испорченном теле — подписывается не тело")
	}
}

func keysOf(m map[string][]byte) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	slices.Sort(out)
	return out
}

func sha1Sum(b []byte) []byte {
	sum := sha1.Sum(b)
	return sum[:]
}

func mustGunzip(t *testing.T, b []byte) []byte {
	t.Helper()
	zr, err := gzip.NewReader(bytes.NewReader(b))
	if err != nil {
		t.Fatalf("gzip.NewReader: %v", err)
	}
	defer zr.Close()
	out, err := io.ReadAll(zr)
	if err != nil {
		t.Fatalf("gunzip: %v", err)
	}
	return out
}

// errSignFail — синтетическая ошибка подписчика.
var errSignFail = errors.New("synthetic signer failure")

// failRsaSigner — подписчик, падающий на подписи индекса.
type failRsaSigner struct{ err error }

func (f failRsaSigner) SignSHA1DigestInfo(context.Context, []byte) ([]byte, error) {
	return nil, f.err
}
func (failRsaSigner) SignSHA256(context.Context, []byte) ([]byte, error) { return nil, nil }
func (failRsaSigner) SignSHA256SHA1DigestInfo(context.Context, []byte) ([]byte, error) {
	return nil, nil
}
func (failRsaSigner) PublicKeyPEM() ([]byte, error) { return nil, nil }

func TestGenerateIndexesSignedSignerErrorFails(t *testing.T) {
	t.Parallel()
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo.apk", pkginfoText)
	g := &Generator{rsa: failRsaSigner{err: errSignFail}}
	err := g.GenerateIndexes(context.Background(), repo, storage, nil)
	if !errors.Is(err, errSignFail) {
		t.Fatalf("ожидали errSignFail, got %v", err)
	}
	// Индекс не записан: подпись нужна в том же файле, что и тело.
	if _, err := storage.Get(context.Background(), "repo/1/apk/x86_64/apkindex.tar.gz"); err == nil {
		t.Error("индекс записан несмотря на сбой подписи")
	}
}

func TestSetRsaSigner(t *testing.T) {
	t.Parallel()
	g := &Generator{}
	if g.rsa != nil {
		t.Fatal("новый Generator уже имеет rsa-подписчик")
	}
	g.SetRsaSigner(newTestRsaSigner(t))
	if g.rsa == nil {
		t.Error("SetRsaSigner не сохранил подписчик")
	}
}

// errListFail — синтетический сбой листинга носителя (см. Storage.List
// контракт: терминальная ошибка вместо пустого обхода).
var errListFail = errors.New("synthetic listing failure")

// failingListStorage — FakeStorage с отказом List: Get/Put честные,
// перечисление падает. Проверяет fail-closed генератора изолированно
// от носителя.
type failingListStorage struct {
	*testutil.FakeStorage
	err error
}

func (f *failingListStorage) List(_ context.Context, _ string) iter.Seq2[port.Meta, error] {
	return func(yield func(port.Meta, error) bool) {
		yield(port.Meta{}, f.err)
	}
}

// TestGenerateIndexesListingErrorKeepsOldIndexes — при ошибке листинга
// генерация падает, прежний APKINDEX остаётся байт-в-байт (fail-closed:
// транзиентный сбой носителя не «опустошает» репо).
func TestGenerateIndexesListingErrorKeepsOldIndexes(t *testing.T) {
	t.Parallel()
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo.apk", pkginfoText)

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("первая генерация: %v", err)
	}
	const indexKey = "repo/1/apk/x86_64/apkindex.tar.gz"
	before := readStorage(t, storage, indexKey)

	broken := &failingListStorage{FakeStorage: storage, err: errListFail}
	err := g.GenerateIndexes(context.Background(), repo, broken, nil)
	if err == nil || !errors.Is(err, errListFail) {
		t.Fatalf("ожидали errListFail из листинга, получено %v", err)
	}
	after := readStorage(t, storage, indexKey)
	if !bytes.Equal(before, after) {
		t.Fatal("ошибка листинга перезаписала валидный APKINDEX (не fail-closed)")
	}
}

// TestGenerateIndexesDependencies — зависимостям из .PKGINFO место в
// APKINDEX (D:/p:/i:, space-joined): без них `apk add` не резолвит
// зависимости из личного репо.
func TestGenerateIndexesDependencies(t *testing.T) {
	t.Parallel()
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	pkginfo := "pkgname = foo\npkgver = 1.0-r0\narch = x86_64\n" +
		"depend = so:libc.musl-x86_64.so.1\n" +
		"depend = musl\n" +
		"provides = cmd:foo=1.0-r0\n" +
		"install_if = foo-doc musl\n"
	putApk(t, storage, repo, "x86_64/foo-1.0-r0.apk", pkginfo)

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}

	idxGz := readStorage(t, storage, "repo/1/apk/x86_64/apkindex.tar.gz")
	gz, err := gzip.NewReader(bytes.NewReader(idxGz))
	if err != nil {
		t.Fatalf("gzip.NewReader: %v", err)
	}
	text, err := extractAPKINDEXText(gz)
	if err != nil {
		t.Fatalf("extractAPKINDEXText: %v", err)
	}
	for _, want := range []string{
		"D:so:libc.musl-x86_64.so.1 musl\n",
		"p:cmd:foo=1.0-r0\n",
		"i:foo-doc musl\n",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("APKINDEX не содержит %q:\n%s", want, text)
		}
	}
}

// TestGenerateIndexesNoDependenciesOmitsLines — без depend/provides/
// install_if в .PKGINFO строки D:/p:/i: не эмитятся (пустые D: ломают
// строгие парсеры клиентов).
func TestGenerateIndexesNoDependenciesOmitsLines(t *testing.T) {
	t.Parallel()
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo-1.0-r0.apk", "pkgname = foo\npkgver = 1.0-r0\narch = x86_64\n")

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}
	idxGz := readStorage(t, storage, "repo/1/apk/x86_64/apkindex.tar.gz")
	gz, err := gzip.NewReader(bytes.NewReader(idxGz))
	if err != nil {
		t.Fatalf("gzip.NewReader: %v", err)
	}
	text, err := extractAPKINDEXText(gz)
	if err != nil {
		t.Fatalf("extractAPKINDEXText: %v", err)
	}
	for _, banned := range []string{"D:", "p:", "i:"} {
		if strings.Contains(text, banned+"\n") || strings.Contains(text, "\n"+banned) {
			t.Errorf("APKINDEX содержит %q без зависимостей в пакете:\n%s", banned, text)
		}
	}
}

// apkBombGz строит .apk-бомбу (gzip-вариант — его формат): tar с одним
// членом объявленного размера huge, набитым повторами (сжимается в
// килобайты, разжимается больше капа). Запись потоковая через компрессор
// — память теста ограничена буфером, а не размером бомбы (по образцу
// apt controlBombGz).
func apkBombGz(t *testing.T, huge int64) []byte {
	t.Helper()
	return apkBombCompressed(t, huge, true)
}

// apkBombZst — zstd-твин apkBombGz (верификация Р6: кап есть во всех
// трёх ветвях decompressApk, а бомба-тест был только на gzip; apt
// закрыл тот же гэп controlBombZstd — урок «фикс класса: твин-тест»).
func apkBombZst(t *testing.T, huge int64) []byte {
	t.Helper()
	return apkBombCompressed(t, huge, false)
}

func apkBombCompressed(t *testing.T, huge int64, gz bool) []byte {
	t.Helper()
	var raw bytes.Buffer
	var comp io.WriteCloser
	if gz {
		comp = gzip.NewWriter(&raw)
	} else {
		// SpeedFastest: бомба гигабайтного класса, дефолтный уровень
		// сжатия делал бы сборку теста секундной (pacman pkgBombZst —
		// тот же выбор).
		enc, err := zstd.NewWriter(&raw, zstd.WithEncoderLevel(zstd.SpeedFastest))
		if err != nil {
			t.Fatalf("zstd.NewWriter: %v", err)
		}
		comp = enc
	}
	tw := tar.NewWriter(comp)
	if err := tw.WriteHeader(&tar.Header{Name: "bomb", Mode: 0o644, Size: huge, Typeflag: tar.TypeReg}); err != nil {
		t.Fatalf("tw.WriteHeader: %v", err)
	}
	chunk := bytes.Repeat([]byte{'A'}, 64<<10)
	var written int64
	for written+int64(len(chunk)) <= huge {
		if _, err := tw.Write(chunk); err != nil {
			t.Fatalf("tw.Write: %v", err)
		}
		written += int64(len(chunk))
	}
	if rest := huge - written; rest > 0 {
		if _, err := tw.Write(bytes.Repeat([]byte{'A'}, int(rest))); err != nil {
			t.Fatalf("tw.Write rest: %v", err)
		}
	}
	if err := tw.Close(); err != nil {
		t.Fatalf("tw.Close: %v", err)
	}
	if err := comp.Close(); err != nil {
		t.Fatalf("comp.Close: %v", err)
	}
	return raw.Bytes()
}

// TestDecompressApkBomb — внешний ревью, раунд 5: reindex-путь apk
// декомпрессии без капа (ParseAPKINDEX каплен, генератор нет). Бомба
// (разжатых > maxDecompressedApk) — ErrDecompressTooLarge за лимитом,
// а не OOM. Счётчик лимитера доказывает отказ в процессе чтения:
// gzip синхронен, поэтому ассертим точный «кап+δ» (по образцу apt
// gz-теста, δ = буфер одного чтения). Чтение — io.Copy(io.Discard):
// ReadAll копил бы гигабайты разжатой бомбы в памяти самого теста
// (OOM-килл на CI-runner'е с 8 ГБ, см. pacman-замер VmHWM 13 GiB).
func TestDecompressApkBomb(t *testing.T) {
	t.Parallel()
	// Кап уменьшен (4 MiB против прод-дефолта 1 GiB): та же ветка
	// limitedReader-отказа, без гигабайтной декомпрессии под -race.
	const cap = int64(4 << 20)
	const huge = cap + (1 << 20)
	dr, err := decompressApk(bufio.NewReader(bytes.NewReader(apkBombGz(t, huge))), cap)
	if err != nil {
		t.Fatalf("decompressApk: %v", err)
	}
	defer dr.Close()
	lr, ok := dr.(*limitedReadCloser)
	if !ok {
		t.Fatalf("decompressApk вернул %T, хочу *limitedReadCloser", dr)
	}
	if _, err := io.Copy(io.Discard, dr); !errors.Is(err, ErrDecompressTooLarge) {
		t.Fatalf("ожидали ErrDecompressTooLarge на чтении, получили %v", err)
	}
	if want := cap + 8192; lr.n > want {
		t.Errorf("разжато %d байт, хочу не более ~%d (кап + буфер)", lr.n, want)
	}
}

// TestGenerateIndexesApkBomb — reindex с бомбой-пакетом: задача failed
// с ошибкой декомпресс-лимита, индексы не закоммичены (пишутся только
// после успешного прохода всех .apk).
func TestGenerateIndexesApkBomb(t *testing.T) {
	t.Parallel()
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	// Кап 4 MiB инжектом (прод-дефолт 1 GiB): контракт тот же — задача
	// failed с ErrDecompressTooLarge, индексы не закоммичены.
	const cap = int64(4 << 20)
	bomb := apkBombGz(t, cap+(1<<20))
	key := port.RepoPrefix(repo) + "/x86_64/bomb-1.0-r0.apk"
	w, err := storage.Put(context.Background(), key)
	if err != nil {
		t.Fatalf("storage.Put %s: %v", key, err)
	}
	if _, err := w.Write(bomb); err != nil {
		t.Fatalf("w.Write: %v", err)
	}
	if err := w.Commit(context.Background()); err != nil {
		t.Fatalf("w.Commit: %v", err)
	}

	err = (&Generator{decompressLimit: cap}).GenerateIndexes(context.Background(), repo, storage, nil)
	if !errors.Is(err, ErrDecompressTooLarge) {
		t.Fatalf("ожидали ErrDecompressTooLarge, получили %v", err)
	}
	if _, err := storage.Get(context.Background(), "repo/1/apk/x86_64/apkindex.tar.gz"); err == nil {
		t.Error("индекс не должен быть закоммичен")
	}
}

// TestGenerateIndexesZstdBomb — верификация Р6: zstd-ветка decompressApk
// без бомба-теста (кап есть во всех трёх ветвях, тест был только на
// gzip; apt закрыл тот же гэп controlBombZstd — урок «фикс класса:
// твин-тест»). Бомба 2× капа: упреждение zstd-декодера (MiB-класс,
// замер на apt ~0.9 МиБ) на порядки меньше запаса, поэтому ассертим
// «бомба не дочитана», а не точный «кап+δ» (тот честен только у
// синхронного gzip). Чтение — io.Copy(io.Discard): ReadAll копил бы
// гигабайты разжатой бомбы в памяти теста (OOM на CI-runner'е, см.
// pacman-замер VmHWM). Плюс сквозной путь reindex: задача failed,
// индексы не закоммичены.
func TestGenerateIndexesZstdBomb(t *testing.T) {
	t.Parallel()
	// Кап уменьшен (4 MiB против прод-дефолта 1 GiB): та же zstd-ветка
	// limitedReader-отказа, бомба 2× капа — ассерты неизменны.
	const cap = int64(4 << 20)
	const huge = 2 * cap
	dr, err := decompressApk(bufio.NewReader(bytes.NewReader(apkBombZst(t, huge))), cap)
	if err != nil {
		t.Fatalf("decompressApk: %v", err)
	}
	lr, ok := dr.(*limitedReadCloser)
	if !ok {
		t.Fatalf("decompressApk вернул %T, хочу *limitedReadCloser", dr)
	}
	if _, err := io.Copy(io.Discard, dr); !errors.Is(err, ErrDecompressTooLarge) {
		t.Fatalf("ожидали ErrDecompressTooLarge на чтении, получили %v", err)
	}
	if lr.n >= huge {
		t.Errorf("разжато %d из %d байт — отказ обязан наступить до конца бомбы", lr.n, huge)
	}
	if err := dr.Close(); err != nil {
		t.Fatalf("dr.Close: %v", err)
	}

	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	bomb := apkBombZst(t, huge)
	key := port.RepoPrefix(repo) + "/x86_64/bomb-1.0-r0.apk"
	w, err := storage.Put(context.Background(), key)
	if err != nil {
		t.Fatalf("storage.Put %s: %v", key, err)
	}
	if _, err := w.Write(bomb); err != nil {
		t.Fatalf("w.Write: %v", err)
	}
	if err := w.Commit(context.Background()); err != nil {
		t.Fatalf("w.Commit: %v", err)
	}

	err = (&Generator{decompressLimit: cap}).GenerateIndexes(context.Background(), repo, storage, nil)
	if !errors.Is(err, ErrDecompressTooLarge) {
		t.Fatalf("ожидали ErrDecompressTooLarge, получили %v", err)
	}
	if _, err := storage.Get(context.Background(), "repo/1/apk/x86_64/apkindex.tar.gz"); err == nil {
		t.Error("индекс не должен быть закоммичен")
	}
}

// TestReadPkgInfoCancelDuringDecompress — отмена reindex-задачи гасит
// декомпрессию: ctx.Err() проверяется на каждом члене tar-потока, а не
// только между пакетами (раунд 5). Честный пакет с отменённым контекстом
// отказывается до первого tr.Next.
func TestReadPkgInfoCancelDuringDecompress(t *testing.T) {
	t.Parallel()
	apk := buildApkTarGz(t, pkginfoText)
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	_, err := readPkgInfoFromPackage(ctx, bytes.NewReader(apk), 0)
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("ожидали context.Canceled, получили %v", err)
	}
}

// gateReader отменяет ctx один раз после доставки gate байт и считает
// отданное: cancel-барьер в середине tar-потока. После отмены байты
// продолжают отдаваться — если код читает поток дальше, счётчик served
// это покажет.
type gateReader struct {
	r      io.Reader
	gate   int64
	served int64
	cancel context.CancelFunc
	fired  bool
}

func (g *gateReader) Read(p []byte) (int, error) {
	n, err := g.r.Read(p)
	g.served += int64(n)
	if !g.fired && g.served >= g.gate {
		g.fired = true
		g.cancel()
	}
	return n, err
}

// TestReadPkgInfoCancelMidStream — mid-stream вариант cancel-теста:
// отмена ДО вызова не отличает «ctx на каждом члене» от «ctx на входе»
// (верификация Р6). Несжатый tar с тремя членами (два заполнителя,
// .PKGINFO последним); gate-ридер отменяет ctx сразу после доставки
// первого члена (его заголовок — ровно 512 байт). Контракт: Canceled,
// а не успешный разбор — при «проверке на входе» .PKGINFO третьего
// члена был бы найден без ошибки; счётчик gate-ридера доказывает, что
// члены после отмены не доставлялись.
func TestReadPkgInfoCancelMidStream(t *testing.T) {
	t.Parallel()
	var buf bytes.Buffer
	tw := tar.NewWriter(&buf)
	for _, name := range []string{"usr/bin/a", "usr/bin/b", ".PKGINFO"} {
		var content []byte
		if name == ".PKGINFO" {
			content = []byte(pkginfoText)
		}
		if err := tw.WriteHeader(&tar.Header{Name: name, Typeflag: tar.TypeReg, Mode: 0o644, Size: int64(len(content))}); err != nil {
			t.Fatalf("WriteHeader %s: %v", name, err)
		}
		if len(content) > 0 {
			if _, err := tw.Write(content); err != nil {
				t.Fatalf("Write .PKGINFO: %v", err)
			}
		}
	}
	if err := tw.Close(); err != nil {
		t.Fatalf("tw.Close: %v", err)
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	g := &gateReader{r: bytes.NewReader(buf.Bytes()), gate: 512, cancel: cancel}
	_, err := readPkgInfoFromTar(ctx, g)
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("ожидали context.Canceled, получили %v", err)
	}
	if g.served > 512 {
		t.Errorf("доставлено %d байт — члены после первого не должны читаться", g.served)
	}
}

// indexPaths — отсортированные пути F: индекса по ключу storage
// (roundtrip через ParseAPKINDEX).
func indexPaths(t *testing.T, storage *testutil.FakeStorage, key string) []string {
	t.Helper()
	entries, err := collectIndex(ParseAPKINDEX(bytes.NewReader(readStorage(t, storage, key))))
	if err != nil {
		t.Fatalf("ParseAPKINDEX %s: %v", key, err)
	}
	out := make([]string, 0, len(entries))
	for _, e := range entries {
		out = append(out, e.FilePath)
	}
	slices.Sort(out)
	return out
}

// TestGenerateIndexesPerArch — раскладка по архитектурам (сессия 192):
// индекс на архитектуру в <prefix>/<arch>/apkindex.tar.gz, в корне репо
// индекса больше нет (прежняя схема — источник 404 живого клиента).
func TestGenerateIndexesPerArch(t *testing.T) {
	t.Parallel()
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo-1.0-r0.apk", "pkgname = foo\npkgver = 1.0-r0\narch = x86_64\n")
	putApk(t, storage, repo, "aarch64/bar-2.0-r1.apk", "pkgname = bar\npkgver = 2.0-r1\narch = aarch64\n")

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}

	if got := indexPaths(t, storage, "repo/1/apk/x86_64/apkindex.tar.gz"); !slices.Equal(got, []string{"x86_64/foo-1.0-r0.apk"}) {
		t.Errorf("индекс x86_64 = %v, хочу [x86_64/foo-1.0-r0.apk]", got)
	}
	if got := indexPaths(t, storage, "repo/1/apk/aarch64/apkindex.tar.gz"); !slices.Equal(got, []string{"aarch64/bar-2.0-r1.apk"}) {
		t.Errorf("индекс aarch64 = %v, хочу [aarch64/bar-2.0-r1.apk]", got)
	}
	if _, err := storage.Get(context.Background(), "repo/1/apk/apkindex.tar.gz"); err == nil {
		t.Error("индекс в корне репо всё ещё пишется")
	}
}

// TestGenerateIndexesNoarchInEveryArchIndex — noarch-запись нужна в КАЖДОМ
// arch-индексе: клиент читает индекс только своей архитектуры, а файл
// noarch-пакета тянет из <repo>/noarch/ (факт пробы сессии 192).
func TestGenerateIndexesNoarchInEveryArchIndex(t *testing.T) {
	t.Parallel()
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo-1.0-r0.apk", "pkgname = foo\npkgver = 1.0-r0\narch = x86_64\n")
	putApk(t, storage, repo, "aarch64/bar-2.0-r1.apk", "pkgname = bar\npkgver = 2.0-r1\narch = aarch64\n")
	putApk(t, storage, repo, "noarch/data-3.0-r0.apk", "pkgname = data\npkgver = 3.0-r0\narch = noarch\n")

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}
	if got := indexPaths(t, storage, "repo/1/apk/x86_64/apkindex.tar.gz"); !slices.Equal(got, []string{"noarch/data-3.0-r0.apk", "x86_64/foo-1.0-r0.apk"}) {
		t.Errorf("индекс x86_64 = %v, хочу свою запись + noarch", got)
	}
	if got := indexPaths(t, storage, "repo/1/apk/aarch64/apkindex.tar.gz"); !slices.Equal(got, []string{"aarch64/bar-2.0-r1.apk", "noarch/data-3.0-r0.apk"}) {
		t.Errorf("индекс aarch64 = %v, хочу свою запись + noarch", got)
	}
	if got := indexPaths(t, storage, "repo/1/apk/noarch/apkindex.tar.gz"); !slices.Equal(got, []string{"noarch/data-3.0-r0.apk"}) {
		t.Errorf("индекс noarch = %v, хочу только noarch-запись", got)
	}
}

// TestGenerateIndexesSkipsApkOutsideItsArchDir — пакет в каталоге чужой
// архитектуры (или в корне репо) клиенту недоступен: URL пакета клиент
// собирает как <repo>/<A: .PKGINFO>/<basename(F:)>, поэтому запись в
// индекс не попадает, а факт уходит в лог.
func TestGenerateIndexesSkipsApkOutsideItsArchDir(t *testing.T) {
	t.Parallel()
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo-1.0-r0.apk", "pkgname = foo\npkgver = 1.0-r0\narch = x86_64\n")
	putApk(t, storage, repo, "x86_64/foreign-1.0-r0.apk", "pkgname = foreign\npkgver = 1.0-r0\narch = aarch64\n")
	putApk(t, storage, repo, "rooted-1.0-r0.apk", "pkgname = rooted\npkgver = 1.0-r0\narch = x86_64\n")

	rec := &recordingProgress{}
	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, rec); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}
	if got := indexPaths(t, storage, "repo/1/apk/x86_64/apkindex.tar.gz"); !slices.Equal(got, []string{"x86_64/foo-1.0-r0.apk"}) {
		t.Errorf("индекс x86_64 = %v, хочу только пакет в каталоге своей архитектуры", got)
	}
	if _, err := storage.Get(context.Background(), "repo/1/apk/aarch64/apkindex.tar.gz"); err == nil {
		t.Error("индекс aarch64 создан из пакета в чужом каталоге")
	}
	if !slices.ContainsFunc(rec.logs, func(s string) bool { return strings.Contains(s, "пропущен") }) {
		t.Errorf("нет лога о пропуске: %v", rec.logs)
	}
}

// gzBytes — gzip-обёртка блоба (каждый член .apk — самостоятельный gzip-поток).
func gzBytes(t *testing.T, raw []byte) []byte {
	t.Helper()
	var out bytes.Buffer
	gz := gzip.NewWriter(&out)
	if _, err := gz.Write(raw); err != nil {
		t.Fatalf("gzip write: %v", err)
	}
	if err := gz.Close(); err != nil {
		t.Fatalf("gzip close: %v", err)
	}
	return out.Bytes()
}

// apkTarEntry — сегмент непрерывного tar-потока .apk: заголовок + содержимое
// с выравниванием до 512 байт (без завершающих нулевых блоков — их несёт
// только последняя секция).
func apkTarEntry(t *testing.T, name, content string) []byte {
	t.Helper()
	var buf bytes.Buffer
	tw := tar.NewWriter(&buf)
	if err := tw.WriteHeader(&tar.Header{
		Name: name, Typeflag: tar.TypeReg, Mode: 0o644, Size: int64(len(content)),
	}); err != nil {
		t.Fatalf("tar header %s: %v", name, err)
	}
	if _, err := tw.Write([]byte(content)); err != nil {
		t.Fatalf("tar write %s: %v", name, err)
	}
	if err := tw.Close(); err != nil {
		t.Fatalf("tar close %s: %v", name, err)
	}
	raw := buf.Bytes()
	// tar.Writer закрывает архив двумя нулевыми блоками (1024); сегменту
	// непрерывного потока они не нужны — остаток уже выровнен до 512.
	return raw[:len(raw)-1024]
}

// apkGzMember собирает gzip-член .apk с завершённым tar-архивом из одного
// файла (неподписанный пакет, член без .PKGINFO).
func apkGzMember(t *testing.T, name, content string) []byte {
	t.Helper()
	var tarBuf bytes.Buffer
	tw := tar.NewWriter(&tarBuf)
	if err := tw.WriteHeader(&tar.Header{
		Name: name, Typeflag: tar.TypeReg, Mode: 0o644, Size: int64(len(content)),
	}); err != nil {
		t.Fatalf("tar header %s: %v", name, err)
	}
	if _, err := tw.Write([]byte(content)); err != nil {
		t.Fatalf("tar write %s: %v", name, err)
	}
	if err := tw.Close(); err != nil {
		t.Fatalf("tar close: %v", err)
	}
	return gzBytes(t, tarBuf.Bytes())
}

// signedApk собирает подписанный .apk по живому образцу (факт пробы:
// tree-2.2.1-r0 — три gzip-члена 665/572/29079 байт): ОДИН непрерывный
// tar-поток (сигнатура, control, данные), разрезанный на gzip-члены по
// границам секций, tar внутри членов не терминирован. Возвращает байты .apk
// и СЖАТЫЕ байты control-члена — эталон C: тест считает по ним, независимо
// от обхода генератора.
func signedApk(t *testing.T, pkginfo string) (apk, controlMember []byte) {
	t.Helper()
	sig := gzBytes(t, apkTarEntry(t, "./.SIGN.RSA.alpine-devel@lists.alpinelinux.org-6165ee59.rsa.pub", "signature-bytes"))
	control := gzBytes(t, apkTarEntry(t, "./.PKGINFO", pkginfo))
	// Хвост tar-архива: запись данных + два нулевых блока.
	data := append(apkTarEntry(t, "./usr/bin/foo", "payload-bytes"), make([]byte, 1024)...)
	out := make([]byte, 0, len(sig)+len(control)+len(data))
	out = append(out, sig...)
	out = append(out, control...)
	out = append(out, gzBytes(t, data)...)
	return out, control
}

// putApkBytes складывает готовые .apk-байты в FakeStorage.
func putApkBytes(t *testing.T, storage *testutil.FakeStorage, repo domain.Repo, name string, apk []byte) string {
	t.Helper()
	key := port.RepoPrefix(repo) + "/" + name
	w, err := storage.Put(context.Background(), key)
	if err != nil {
		t.Fatalf("storage.Put %s: %v", key, err)
	}
	if _, err := w.Write(apk); err != nil {
		t.Fatalf("w.Write %s: %v", key, err)
	}
	if err := w.Commit(context.Background()); err != nil {
		t.Fatalf("w.Commit %s: %v", key, err)
	}
	return key
}

// indexTextOf разжимает APKINDEX.tar.gz из storage и возвращает текст
// APKINDEX (K:V-записи).
func indexTextOf(t *testing.T, storage *testutil.FakeStorage, key string) string {
	t.Helper()
	gz, err := gzip.NewReader(bytes.NewReader(readStorage(t, storage, key)))
	if err != nil {
		t.Fatalf("gzip.NewReader %s: %v", key, err)
	}
	defer func() { _ = gz.Close() }()
	text, err := extractAPKINDEXText(gz)
	if err != nil {
		t.Fatalf("extractAPKINDEXText %s: %v", key, err)
	}
	return text
}

// recordField вынимает поле записи APKINDEX пакета pkg (field с двоеточием,
// например «C:»).
func recordField(t *testing.T, text, pkg, field string) string {
	t.Helper()
	for _, block := range strings.Split(text, "\n\n") {
		if !strings.Contains("\n"+block+"\n", "\nP:"+pkg+"\n") {
			continue
		}
		for _, line := range strings.Split(block, "\n") {
			if strings.HasPrefix(line, field) {
				return line[len(field):]
			}
		}
		t.Fatalf("у записи %q нет поля %q:\n%s", pkg, field, block)
	}
	t.Fatalf("запись %q не найдена в APKINDEX:\n%s", pkg, text)
	return ""
}

// q1sha1 — эталон чексуммы apk v2 по сжатым байтам секции.
func q1sha1(b []byte) string {
	sum := sha1.Sum(b)
	return "Q1" + base64.StdEncoding.EncodeToString(sum[:])
}

// TestGenerateIndexesChecksumControlSection — C: записи = Q1+base64(sha1
// СЖАТЫХ байт control-члена), а не хеш всего .apk (сессия 193). Эталон
// теста — вручную собранный control-член, посчитанный независимо от
// генератора. Красный до фикса: прежний C: совпадал с sha1 всего файла и
// клиент падал на сверке (BAD signature / v2 package integrity error).
func TestGenerateIndexesChecksumControlSection(t *testing.T) {
	t.Parallel()
	pkginfo := "pkgname = apk-example\npkgver = 1.0-r0\narch = x86_64\n"
	signed, signedControl := signedApk(t, pkginfo)
	unsigned := apkGzMember(t, "./.PKGINFO", pkginfo)

	cases := []struct {
		name    string
		apk     []byte
		control []byte
	}{
		{"подписанный (три члена)", signed, signedControl},
		{"неподписанный (один член)", unsigned, unsigned},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
			storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
			repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
			putApkBytes(t, storage, repo, "x86_64/apk-example-1.0-r0.apk", tc.apk)

			g := &Generator{}
			if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
				t.Fatalf("GenerateIndexes: %v", err)
			}
			text := indexTextOf(t, storage, "repo/1/apk/x86_64/apkindex.tar.gz")

			want := q1sha1(tc.control)
			got := recordField(t, text, "apk-example", "C:")
			if got != want {
				t.Errorf("C: = %q, хочу %q (sha1 сжатых байт control-члена)", got, want)
			}
			if whole := q1sha1(tc.apk); len(tc.control) != len(tc.apk) && got == whole {
				t.Errorf("C: = %q — это хеш ВСЕГО файла, прежняя неверная семантика", got)
			}
			if s := recordField(t, text, "apk-example", "S:"); s != strconv.Itoa(len(tc.apk)) {
				t.Errorf("S: = %q, хочу %d (размер всего файла)", s, len(tc.apk))
			}
		})
	}
}

// TestGenerateIndexesRealAlpineChecksum — живой эталон: реальный подписанный
// пакет Alpine (tree-2.2.1-r0, dl-cdn v3.21) лежит в testdata; C: записи
// обязан дословно совпасть с C: апстримного APKINDEX v3.21 (значение
// вшито фактом пробы сессии 193), S: — с размером файла.
func TestGenerateIndexesRealAlpineChecksum(t *testing.T) {
	t.Parallel()
	const (
		upstreamC = "Q1wy4tW58wERw5iTHp/49JdZLr914="
		fileSize  = 30316
	)
	apkBytes, err := os.ReadFile(filepath.Clean("testdata/tree-2.2.1-r0.apk"))
	if err != nil {
		t.Fatalf("чтение фикстуры: %v", err)
	}
	if len(apkBytes) != fileSize {
		t.Fatalf("фикстура %d байт, ждал %d", len(apkBytes), fileSize)
	}
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApkBytes(t, storage, repo, "x86_64/tree-2.2.1-r0.apk", apkBytes)

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}
	text := indexTextOf(t, storage, "repo/1/apk/x86_64/apkindex.tar.gz")
	if got := recordField(t, text, "tree", "C:"); got != upstreamC {
		t.Errorf("C: = %q, хочу апстримное %q", got, upstreamC)
	}
	if s := recordField(t, text, "tree", "S:"); s != strconv.Itoa(fileSize) {
		t.Errorf("S: = %q, хочу %d", s, fileSize)
	}
}

// TestReadGzipControlSectionSharedBudget — бюджет декомпрессии общий на
// проход, а не на член: две «бомбы» по 700 KiB при капе 1 MiB обязаны
// упереться в лимит (иначе кап умножался бы на число членов, и многочленный
// .apk раздувал бы декомпрессию неограниченно).
func TestReadGzipControlSectionSharedBudget(t *testing.T) {
	t.Parallel()
	const cap = int64(1 << 20)
	const member = 700 << 10
	file := append(apkBombGz(t, member), apkBombGz(t, member)...)

	br := &apkByteReader{src: bytes.NewReader(file), h: sha1.New()}
	if _, err := br.readAhead(4); err != nil && !errors.Is(err, io.EOF) {
		t.Fatalf("readAhead: %v", err)
	}
	if _, _, err := readGzipControlSection(context.Background(), br, cap); !errors.Is(err, ErrDecompressTooLarge) {
		t.Fatalf("ожидали ErrDecompressTooLarge, получили %v", err)
	}
}

// TestReadGzipControlSectionMalformed — битые раскладки не проходят молча:
// обрезанный control-член, мусор вместо tar в члене, пакет без .PKGINFO —
// всё ErrBadApk (и не декомпресс-лимит).
func TestReadGzipControlSectionMalformed(t *testing.T) {
	t.Parallel()
	pkginfo := "pkgname = apk-example\npkgver = 1.0-r0\narch = x86_64\n"
	_, control := signedApk(t, pkginfo)
	sig := apkGzMember(t, "./.SIGN.RSA.foo.rsa.pub", "signature-bytes")
	truncated := append(append([]byte{}, sig...), control[:len(control)/2]...)

	cases := []struct {
		name string
		apk  []byte
	}{
		{"обрезанный control-член", truncated},
		{"мусор вместо tar в члене", gzBytes(t, []byte("not a tar archive at all"))},
		{"пакет без .PKGINFO", apkGzMember(t, "./usr/bin/foo", "payload-bytes")},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			br := &apkByteReader{src: bytes.NewReader(tc.apk), h: sha1.New()}
			if _, err := br.readAhead(4); err != nil && !errors.Is(err, io.EOF) {
				t.Fatalf("readAhead: %v", err)
			}
			_, _, err := readGzipControlSection(context.Background(), br, 0)
			if !errors.Is(err, ErrBadApk) {
				t.Errorf("ожидали ErrBadApk, получили %v", err)
			}
			if errors.Is(err, ErrDecompressTooLarge) {
				t.Errorf("лимит декомпрессии не должен срабатывать на этом вводе: %v", err)
			}
		})
	}
}
