// Хражевник — кеш-прокси и зеркало linux-репозиториев
// Copyright (C) 2026 AlexRus1234
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

package apk

import (
	"archive/tar"
	"bufio"
	"bytes"
	"compress/gzip"
	"context"
	"errors"
	"fmt"
	"io"
	"iter"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/klauspost/compress/zstd"

	"khrazhevnik/internal/core/domain"
	"khrazhevnik/internal/core/port"
	"khrazhevnik/internal/testutil"
)

// buildApkTarGz собирает .apk (v2): gzip+tar с .PKGINFO + один data-файл.
func buildApkTarGz(t *testing.T, pkginfo string) []byte {
	t.Helper()
	return buildApkCompressed(t, pkginfo, true)
}

// buildApkTarZst собирает .apk (v3): zstd+tar с .PKGINFO.
func buildApkTarZst(t *testing.T, pkginfo string) []byte {
	t.Helper()
	return buildApkCompressed(t, pkginfo, false)
}

func buildApkCompressed(t *testing.T, pkginfo string, gzipFlag bool) []byte {
	t.Helper()
	var tarBuf bytes.Buffer
	tw := tar.NewWriter(&tarBuf)
	content := []byte(pkginfo)
	if err := tw.WriteHeader(&tar.Header{
		Name: ".PKGINFO", Typeflag: tar.TypeReg, Mode: 0o644, Size: int64(len(content)),
	}); err != nil {
		t.Fatal(err)
	}
	if _, err := tw.Write(content); err != nil {
		t.Fatal(err)
	}
	if err := tw.WriteHeader(&tar.Header{
		Name: "usr/bin/foo", Typeflag: tar.TypeReg, Mode: 0o755, Size: 0,
	}); err != nil {
		t.Fatal(err)
	}
	if err := tw.Close(); err != nil {
		t.Fatal(err)
	}
	var out bytes.Buffer
	if gzipFlag {
		gz := gzip.NewWriter(&out)
		if _, err := gz.Write(tarBuf.Bytes()); err != nil {
			t.Fatal(err)
		}
		if err := gz.Close(); err != nil {
			t.Fatal(err)
		}
	} else {
		zw, err := zstd.NewWriter(&out)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := zw.Write(tarBuf.Bytes()); err != nil {
			t.Fatal(err)
		}
		if err := zw.Close(); err != nil {
			t.Fatal(err)
		}
	}
	return out.Bytes()
}

const pkginfoText = `# Generated by abuild
pkgname = apk-example
pkgver = 1.0-r0
pkgdesc = example package
url = https://example.com
builddate = 1724323200
packager = Test Packager <test@example.com>
size = 2048
arch = x86_64
license = MIT
origin = apk-example
`

func TestParsePkgInfoGolden(t *testing.T) {
	pi, err := ParsePkgInfo(strings.NewReader(pkginfoText))
	if err != nil {
		t.Fatalf("ParsePkgInfo: %v", err)
	}
	if pi.Name != "apk-example" {
		t.Errorf("Name = %q", pi.Name)
	}
	if pi.Version != "1.0-r0" {
		t.Errorf("Version = %q", pi.Version)
	}
	if pi.Arch != "x86_64" {
		t.Errorf("Arch = %q", pi.Arch)
	}
	if pi.Origin != "apk-example" {
		t.Errorf("Origin = %q", pi.Origin)
	}
	if pi.Size != 2048 {
		t.Errorf("Size = %d", pi.Size)
	}
}

func TestParsePkgInfoMultiLicense(t *testing.T) {
	pi, err := ParsePkgInfo(strings.NewReader("pkgname = foo\nlicense = MIT\nlicense = BSD\n"))
	if err != nil {
		t.Fatal(err)
	}
	if len(pi.License) != 2 || pi.License[0] != "MIT" || pi.License[1] != "BSD" {
		t.Errorf("License = %+v", pi.License)
	}
}

func TestParsePkgInfoCommentsCRLF(t *testing.T) {
	pi, err := ParsePkgInfo(strings.NewReader("# c\r\npkgname = foo\r\n\r\npkgver = 1.0-r0\r\n"))
	if err != nil {
		t.Fatal(err)
	}
	if pi.Name != "foo" || pi.Version != "1.0-r0" {
		t.Errorf("Name=%q Version=%q", pi.Name, pi.Version)
	}
}

func TestParsePkgInfoUnknownKey(t *testing.T) {
	pi, err := ParsePkgInfo(strings.NewReader("futurefield = x\npkgname = bar\n"))
	if err != nil {
		t.Fatal(err)
	}
	if pi.Name != "bar" {
		t.Errorf("Name = %q", pi.Name)
	}
}

func TestParsePkgInfoTooLarge(t *testing.T) {
	big := strings.Repeat("a", maxPkgInfoSize+1)
	_, err := ParsePkgInfo(strings.NewReader(big))
	if !errors.Is(err, ErrPkgInfoTooLarge) {
		t.Fatalf("ожидалась ErrPkgInfoTooLarge, получено %v", err)
	}
}

func TestReadPkgInfoFromPackageGzip(t *testing.T) {
	apk := buildApkTarGz(t, pkginfoText)
	pi, err := readPkgInfoFromPackage(context.Background(), bytes.NewReader(apk))
	if err != nil {
		t.Fatalf("readPkgInfoFromPackage gzip: %v", err)
	}
	if pi.Name != "apk-example" {
		t.Errorf("Name = %q", pi.Name)
	}
}

func TestReadPkgInfoFromPackageZstd(t *testing.T) {
	apk := buildApkTarZst(t, pkginfoText)
	pi, err := readPkgInfoFromPackage(context.Background(), bytes.NewReader(apk))
	if err != nil {
		t.Fatalf("readPkgInfoFromPackage zstd: %v", err)
	}
	if pi.Name != "apk-example" {
		t.Errorf("Name = %q", pi.Name)
	}
}

func TestReadPkgInfoFromTarMissing(t *testing.T) {
	var tarBuf bytes.Buffer
	tw := tar.NewWriter(&tarBuf)
	_ = tw.WriteHeader(&tar.Header{Name: "usr/bin/foo", Typeflag: tar.TypeReg, Mode: 0o755, Size: 0})
	_ = tw.Close()
	_, err := readPkgInfoFromTar(context.Background(), bytes.NewReader(tarBuf.Bytes()))
	if !errors.Is(err, ErrBadApk) {
		t.Fatalf("ожидали ErrBadApk для tar без .PKGINFO, got %v", err)
	}
}

func TestGeneratorName(t *testing.T) {
	g := &Generator{}
	if g.Name() != Name {
		t.Errorf("Name = %q, want %q", g.Name(), Name)
	}
}

func TestValidateObjectPath(t *testing.T) {
	g := &Generator{}
	cases := []struct {
		path string
		want bool
	}{
		{"x86_64/apk-example-1.0-r0.apk", true},
		{"apk-example-1.0-r0.apk", true},
		{"apkindex.tar.gz", false},
		{"apkindex.tar.gz.sig", false},
		{"foo.txt", false},
		{"", false},
	}
	for _, c := range cases {
		err := g.ValidateObjectPath(c.path)
		got := err == nil
		if got != c.want {
			t.Errorf("ValidateObjectPath(%q) = %v, want ok=%v", c.path, err, c.want)
		}
	}
}

// putApk складывает .apk-байты в FakeStorage.
func putApk(t *testing.T, storage *testutil.FakeStorage, repo domain.Repo, name, pkginfo string) string {
	t.Helper()
	apk := buildApkTarGz(t, pkginfo)
	key := port.RepoPrefix(repo) + "/" + name
	w, err := storage.Put(context.Background(), key)
	if err != nil {
		t.Fatalf("storage.Put %s: %v", key, err)
	}
	if _, err := w.Write(apk); err != nil {
		t.Fatalf("w.Write %s: %v", key, err)
	}
	if err := w.Commit(context.Background()); err != nil {
		t.Fatalf("w.Commit %s: %v", key, err)
	}
	return key
}

func readStorage(t *testing.T, storage *testutil.FakeStorage, key string) []byte {
	t.Helper()
	obj, err := storage.Get(context.Background(), key)
	if err != nil {
		t.Fatalf("Get %s: %v", key, err)
	}
	defer obj.Body.Close()
	b, err := io.ReadAll(obj.Body)
	if err != nil {
		t.Fatalf("ReadAll %s: %v", key, err)
	}
	return b
}

func TestGenerateIndexesSingleApk(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/apk-example-1.0-r0.apk", pkginfoText)

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}

	// APKINDEX.tar.gz: gzip+tar с файлом APKINDEX. Разжимаем gzip → tar.
	idxGz := readStorage(t, storage, "repo/1/apk/apkindex.tar.gz")
	gz, err := gzip.NewReader(bytes.NewReader(idxGz))
	if err != nil {
		t.Fatalf("gzip.NewReader: %v", err)
	}
	text, err := extractAPKINDEXText(gz)
	if err != nil {
		t.Fatalf("extractAPKINDEXText: %v", err)
	}
	for _, want := range []string{
		"P:apk-example\n",
		"V:1.0-r0\n",
		"A:x86_64\n",
		"T:example package\n",
		"F:x86_64/apk-example-1.0-r0.apk\n",
		"C:Q1",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("APKINDEX не содержит %q:\n%s", want, text)
		}
	}
}

// extractAPKINDEXText находит файл APKINDEX в tar-потоке и возвращает его
// текст (для проверок формата).
func extractAPKINDEXText(r io.Reader) (string, error) {
	tr := tar.NewReader(r)
	for {
		hdr, err := tr.Next()
		if err != nil {
			return "", err
		}
		base := hdr.Name
		if idx := strings.LastIndexByte(base, '/'); idx >= 0 {
			base = base[idx+1:]
		}
		if base == "APKINDEX" {
			b, _ := io.ReadAll(tr)
			return string(b), nil
		}
	}
}

// roundtrip: список .apk → APKINDEX.tar.gz → ParseAPKINDEX → те же F:.
func TestGenerateIndexesRoundtrip(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/apk-example-1.0-r0.apk",
		"pkgname = apk-example\npkgver = 1.0-r0\narch = x86_64\n")
	putApk(t, storage, repo, "x86_64/second-pkg-2.0-r1.apk",
		"pkgname = second-pkg\npkgver = 2.0-r1\narch = any\n")

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}

	idxGz := readStorage(t, storage, "repo/1/apk/apkindex.tar.gz")
	// ParseAPKINDEX сам разжимает gzip; передаём сырые байты.
	entries, err := collectIndex(ParseAPKINDEX(bytes.NewReader(idxGz)))
	if err != nil {
		t.Fatalf("ParseAPKINDEX roundtrip: %v", err)
	}
	paths := map[string]bool{}
	for _, e := range entries {
		paths[e.FilePath] = true
	}
	want := []string{
		"x86_64/apk-example-1.0-r0.apk",
		"x86_64/second-pkg-2.0-r1.apk",
	}
	for _, w := range want {
		if !paths[w] {
			t.Errorf("filepath %q отсутствует в APKINDEX (roundtrip): %+v", w, paths)
		}
	}
}

func TestGenerateIndexesEmptyRepo(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes пустой репо: %v", err)
	}
	idxGz := readStorage(t, storage, "repo/1/apk/apkindex.tar.gz")
	entries, _ := collectIndex(ParseAPKINDEX(bytes.NewReader(idxGz)))
	if len(entries) != 0 {
		t.Errorf("пустой репо дал %d записей, хочу 0", len(entries))
	}
}

func TestGenerateIndexesWrongEcosystem(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: "apt"}
	g := &Generator{}
	err := g.GenerateIndexes(context.Background(), repo, storage, nil)
	var unsup *domain.UnsupportedError
	if !errors.As(err, &unsup) {
		t.Fatalf("ожидали UnsupportedError, получили %v", err)
	}
}

func TestGenerateIndexesContextCanceled(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo.apk", pkginfoText)
	g := &Generator{}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if err := g.GenerateIndexes(ctx, repo, storage, nil); err == nil {
		t.Fatal("ожидали ошибку отменённого контекста")
	}
}

// recordingProgress ловит кадры Update.
type recordingProgress struct {
	updates []string
	logs    []string
}

func (r *recordingProgress) Update(phase, current string, processed, total int64) {
	r.updates = append(r.updates, fmt.Sprintf("%s/%s/%d/%d", phase, current, processed, total))
}
func (r *recordingProgress) Log(line string) { r.logs = append(r.logs, line) }

func TestGenerateIndexesProgress(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo.apk", pkginfoText)
	g := &Generator{}
	rec := &recordingProgress{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, rec); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}
	phases := map[string]bool{}
	for _, u := range rec.updates {
		phases[strings.SplitN(u, "/", 2)[0]] = true
	}
	for _, want := range []string{"enumerate", "pkginfo", "write"} {
		if !phases[want] {
			t.Errorf("фаза %s не отработала: %v", want, rec.updates)
		}
	}
	if !slices.ContainsFunc(rec.logs, func(s string) bool { return strings.Contains(s, "индексы записаны") }) {
		t.Errorf("нет строки завершения: %v", rec.logs)
	}
}

// fakeSigner — port.Signer с детерминированным маркером.
type fakeSigner struct{}

func (fakeSigner) Sign(_ context.Context, _ io.Reader) (io.Reader, error) {
	return bytes.NewReader([]byte("cleartext-stub")), nil
}
func (fakeSigner) SignDetached(_ context.Context, _ io.Reader) (io.Reader, error) {
	return bytes.NewReader([]byte("detached-stub")), nil
}
func (fakeSigner) PublicKey() ([]byte, error) { return []byte("pub-stub"), nil }

func TestGenerateIndexesUnsignedNoSig(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo.apk", pkginfoText)
	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}
	if _, err := storage.Get(context.Background(), "repo/1/apk/apkindex.tar.gz.sig"); err == nil {
		t.Error("без Signer создан apkindex.tar.gz.sig")
	}
}

func TestGenerateIndexesSignedWritesSig(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo.apk", pkginfoText)
	g := &Generator{signer: fakeSigner{}}
	rec := &recordingProgress{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, rec); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}
	sig := readStorage(t, storage, "repo/1/apk/apkindex.tar.gz.sig")
	if string(sig) != "detached-stub" {
		t.Errorf("apkindex.tar.gz.sig = %q, хочу detached-stub", sig)
	}
	phases := map[string]bool{}
	for _, u := range rec.updates {
		phases[strings.SplitN(u, "/", 2)[0]] = true
	}
	if !phases["sign"] {
		t.Errorf("фаза sign не отработала: %v", rec.updates)
	}
}

// errSignFail — синтетическая ошибка подписчика.
var errSignFail = errors.New("synthetic signer failure")

type failSigner struct{}

func (failSigner) Sign(context.Context, io.Reader) (io.Reader, error) { return nil, errSignFail }
func (failSigner) SignDetached(context.Context, io.Reader) (io.Reader, error) {
	return nil, errSignFail
}
func (failSigner) PublicKey() ([]byte, error) { return nil, nil }

func TestGenerateIndexesSignedSignerErrorFails(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo.apk", pkginfoText)
	g := &Generator{signer: failSigner{}}
	err := g.GenerateIndexes(context.Background(), repo, storage, nil)
	if !errors.Is(err, errSignFail) {
		t.Fatalf("ожидали errSignFail, got %v", err)
	}
}

func TestSetSigner(t *testing.T) {
	g := &Generator{}
	if g.signer != nil {
		t.Fatal("новый Generator уже имеет signer")
	}
	s := fakeSigner{}
	g.SetSigner(s)
	if g.signer == nil {
		t.Error("SetSigner не сохранил signer")
	}
}

// errListFail — синтетический сбой листинга носителя (см. Storage.List
// контракт: терминальная ошибка вместо пустого обхода).
var errListFail = errors.New("synthetic listing failure")

// failingListStorage — FakeStorage с отказом List: Get/Put честные,
// перечисление падает. Проверяет fail-closed генератора изолированно
// от носителя.
type failingListStorage struct {
	*testutil.FakeStorage
	err error
}

func (f *failingListStorage) List(_ context.Context, _ string) iter.Seq2[port.Meta, error] {
	return func(yield func(port.Meta, error) bool) {
		yield(port.Meta{}, f.err)
	}
}

// TestGenerateIndexesListingErrorKeepsOldIndexes — при ошибке листинга
// генерация падает, прежний APKINDEX остаётся байт-в-байт (fail-closed:
// транзиентный сбой носителя не «опустошает» репо).
func TestGenerateIndexesListingErrorKeepsOldIndexes(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo.apk", pkginfoText)

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("первая генерация: %v", err)
	}
	const indexKey = "repo/1/apk/apkindex.tar.gz"
	before := readStorage(t, storage, indexKey)

	broken := &failingListStorage{FakeStorage: storage, err: errListFail}
	err := g.GenerateIndexes(context.Background(), repo, broken, nil)
	if err == nil || !errors.Is(err, errListFail) {
		t.Fatalf("ожидали errListFail из листинга, получено %v", err)
	}
	after := readStorage(t, storage, indexKey)
	if !bytes.Equal(before, after) {
		t.Fatal("ошибка листинга перезаписала валидный APKINDEX (не fail-closed)")
	}
}

// TestGenerateIndexesDependencies — зависимостям из .PKGINFO место в
// APKINDEX (D:/p:/i:, space-joined): без них `apk add` не резолвит
// зависимости из личного репо.
func TestGenerateIndexesDependencies(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	pkginfo := "pkgname = foo\npkgver = 1.0-r0\narch = x86_64\n" +
		"depend = so:libc.musl-x86_64.so.1\n" +
		"depend = musl\n" +
		"provides = cmd:foo=1.0-r0\n" +
		"install_if = foo-doc musl\n"
	putApk(t, storage, repo, "x86_64/foo-1.0-r0.apk", pkginfo)

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}

	idxGz := readStorage(t, storage, "repo/1/apk/apkindex.tar.gz")
	gz, err := gzip.NewReader(bytes.NewReader(idxGz))
	if err != nil {
		t.Fatalf("gzip.NewReader: %v", err)
	}
	text, err := extractAPKINDEXText(gz)
	if err != nil {
		t.Fatalf("extractAPKINDEXText: %v", err)
	}
	for _, want := range []string{
		"D:so:libc.musl-x86_64.so.1 musl\n",
		"p:cmd:foo=1.0-r0\n",
		"i:foo-doc musl\n",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("APKINDEX не содержит %q:\n%s", want, text)
		}
	}
}

// TestGenerateIndexesNoDependenciesOmitsLines — без depend/provides/
// install_if в .PKGINFO строки D:/p:/i: не эмитятся (пустые D: ломают
// строгие парсеры клиентов).
func TestGenerateIndexesNoDependenciesOmitsLines(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putApk(t, storage, repo, "x86_64/foo-1.0-r0.apk", "pkgname = foo\npkgver = 1.0-r0\narch = x86_64\n")

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}
	idxGz := readStorage(t, storage, "repo/1/apk/apkindex.tar.gz")
	gz, err := gzip.NewReader(bytes.NewReader(idxGz))
	if err != nil {
		t.Fatalf("gzip.NewReader: %v", err)
	}
	text, err := extractAPKINDEXText(gz)
	if err != nil {
		t.Fatalf("extractAPKINDEXText: %v", err)
	}
	for _, banned := range []string{"D:", "p:", "i:"} {
		if strings.Contains(text, banned+"\n") || strings.Contains(text, "\n"+banned) {
			t.Errorf("APKINDEX содержит %q без зависимостей в пакете:\n%s", banned, text)
		}
	}
}

// apkBombGz строит .apk-бомбу (gzip-вариант — его формат): tar с одним
// членом объявленного размера huge, набитым повторами (сжимается в
// килобайты, разжимается больше капа). Запись потоковая через компрессор
// — память теста ограничена буфером, а не размером бомбы (по образцу
// apt controlBombGz).
func apkBombGz(t *testing.T, huge int64) []byte {
	t.Helper()
	return apkBombCompressed(t, huge, true)
}

// apkBombZst — zstd-твин apkBombGz (верификация Р6: кап есть во всех
// трёх ветвях decompressApk, а бомба-тест был только на gzip; apt
// закрыл тот же гэп controlBombZstd — урок «фикс класса: твин-тест»).
func apkBombZst(t *testing.T, huge int64) []byte {
	t.Helper()
	return apkBombCompressed(t, huge, false)
}

func apkBombCompressed(t *testing.T, huge int64, gz bool) []byte {
	t.Helper()
	var raw bytes.Buffer
	var comp io.WriteCloser
	if gz {
		comp = gzip.NewWriter(&raw)
	} else {
		// SpeedFastest: бомба гигабайтного класса, дефолтный уровень
		// сжатия делал бы сборку теста секундной (pacman pkgBombZst —
		// тот же выбор).
		enc, err := zstd.NewWriter(&raw, zstd.WithEncoderLevel(zstd.SpeedFastest))
		if err != nil {
			t.Fatalf("zstd.NewWriter: %v", err)
		}
		comp = enc
	}
	tw := tar.NewWriter(comp)
	if err := tw.WriteHeader(&tar.Header{Name: "bomb", Mode: 0o644, Size: huge, Typeflag: tar.TypeReg}); err != nil {
		t.Fatalf("tw.WriteHeader: %v", err)
	}
	chunk := bytes.Repeat([]byte{'A'}, 64<<10)
	var written int64
	for written+int64(len(chunk)) <= huge {
		if _, err := tw.Write(chunk); err != nil {
			t.Fatalf("tw.Write: %v", err)
		}
		written += int64(len(chunk))
	}
	if rest := huge - written; rest > 0 {
		if _, err := tw.Write(bytes.Repeat([]byte{'A'}, int(rest))); err != nil {
			t.Fatalf("tw.Write rest: %v", err)
		}
	}
	if err := tw.Close(); err != nil {
		t.Fatalf("tw.Close: %v", err)
	}
	if err := comp.Close(); err != nil {
		t.Fatalf("comp.Close: %v", err)
	}
	return raw.Bytes()
}

// TestDecompressApkBomb — внешний ревью, раунд 5: reindex-путь apk
// декомпрессии без капа (ParseAPKINDEX каплен, генератор нет). Бомба
// (разжатых > maxDecompressedApk) — ErrDecompressTooLarge за лимитом,
// а не OOM. Счётчик лимитера доказывает отказ в процессе чтения:
// gzip синхронен, поэтому ассертим точный «кап+δ» (по образцу apt
// gz-теста, δ = буфер одного чтения). Чтение — io.Copy(io.Discard):
// ReadAll копил бы гигабайты разжатой бомбы в памяти самого теста
// (OOM-килл на CI-runner'е с 8 ГБ, см. pacman-замер VmHWM 13 GiB).
func TestDecompressApkBomb(t *testing.T) {
	const huge = maxDecompressedApk + (1 << 20) // 1 GiB + 1 MiB
	dr, err := decompressApk(bufio.NewReader(bytes.NewReader(apkBombGz(t, huge))))
	if err != nil {
		t.Fatalf("decompressApk: %v", err)
	}
	defer dr.Close()
	lr, ok := dr.(*limitedReadCloser)
	if !ok {
		t.Fatalf("decompressApk вернул %T, хочу *limitedReadCloser", dr)
	}
	if _, err := io.Copy(io.Discard, dr); !errors.Is(err, ErrDecompressTooLarge) {
		t.Fatalf("ожидали ErrDecompressTooLarge на чтении, получили %v", err)
	}
	if want := maxDecompressedApk + 8192; lr.n > want {
		t.Errorf("разжато %d байт, хочу не более ~%d (кап + буфер)", lr.n, want)
	}
}

// TestGenerateIndexesApkBomb — reindex с бомбой-пакетом: задача failed
// с ошибкой декомпресс-лимита, индексы не закоммичены (пишутся только
// после успешного прохода всех .apk).
func TestGenerateIndexesApkBomb(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	bomb := apkBombGz(t, maxDecompressedApk+(1<<20))
	key := port.RepoPrefix(repo) + "/x86_64/bomb-1.0-r0.apk"
	w, err := storage.Put(context.Background(), key)
	if err != nil {
		t.Fatalf("storage.Put %s: %v", key, err)
	}
	if _, err := w.Write(bomb); err != nil {
		t.Fatalf("w.Write: %v", err)
	}
	if err := w.Commit(context.Background()); err != nil {
		t.Fatalf("w.Commit: %v", err)
	}

	err = (&Generator{}).GenerateIndexes(context.Background(), repo, storage, nil)
	if !errors.Is(err, ErrDecompressTooLarge) {
		t.Fatalf("ожидали ErrDecompressTooLarge, получили %v", err)
	}
	if _, err := storage.Get(context.Background(), "repo/1/apk/apkindex.tar.gz"); err == nil {
		t.Error("индекс не должен быть закоммичен")
	}
}

// TestGenerateIndexesZstdBomb — верификация Р6: zstd-ветка decompressApk
// без бомба-теста (кап есть во всех трёх ветвях, тест был только на
// gzip; apt закрыл тот же гэп controlBombZstd — урок «фикс класса:
// твин-тест»). Бомба 2× капа: упреждение zstd-декодера (MiB-класс,
// замер на apt ~0.9 МиБ) на порядки меньше запаса, поэтому ассертим
// «бомба не дочитана», а не точный «кап+δ» (тот честен только у
// синхронного gzip). Чтение — io.Copy(io.Discard): ReadAll копил бы
// гигабайты разжатой бомбы в памяти теста (OOM на CI-runner'е, см.
// pacman-замер VmHWM). Плюс сквозной путь reindex: задача failed,
// индексы не закоммичены.
func TestGenerateIndexesZstdBomb(t *testing.T) {
	const huge = 2 * maxDecompressedApk
	dr, err := decompressApk(bufio.NewReader(bytes.NewReader(apkBombZst(t, huge))))
	if err != nil {
		t.Fatalf("decompressApk: %v", err)
	}
	lr, ok := dr.(*limitedReadCloser)
	if !ok {
		t.Fatalf("decompressApk вернул %T, хочу *limitedReadCloser", dr)
	}
	if _, err := io.Copy(io.Discard, dr); !errors.Is(err, ErrDecompressTooLarge) {
		t.Fatalf("ожидали ErrDecompressTooLarge на чтении, получили %v", err)
	}
	if lr.n >= huge {
		t.Errorf("разжато %d из %d байт — отказ обязан наступить до конца бомбы", lr.n, huge)
	}
	if err := dr.Close(); err != nil {
		t.Fatalf("dr.Close: %v", err)
	}

	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	bomb := apkBombZst(t, huge)
	key := port.RepoPrefix(repo) + "/x86_64/bomb-1.0-r0.apk"
	w, err := storage.Put(context.Background(), key)
	if err != nil {
		t.Fatalf("storage.Put %s: %v", key, err)
	}
	if _, err := w.Write(bomb); err != nil {
		t.Fatalf("w.Write: %v", err)
	}
	if err := w.Commit(context.Background()); err != nil {
		t.Fatalf("w.Commit: %v", err)
	}

	err = (&Generator{}).GenerateIndexes(context.Background(), repo, storage, nil)
	if !errors.Is(err, ErrDecompressTooLarge) {
		t.Fatalf("ожидали ErrDecompressTooLarge, получили %v", err)
	}
	if _, err := storage.Get(context.Background(), "repo/1/apk/apkindex.tar.gz"); err == nil {
		t.Error("индекс не должен быть закоммичен")
	}
}

// TestReadPkgInfoCancelDuringDecompress — отмена reindex-задачи гасит
// декомпрессию: ctx.Err() проверяется на каждом члене tar-потока, а не
// только между пакетами (раунд 5). Честный пакет с отменённым контекстом
// отказывается до первого tr.Next.
func TestReadPkgInfoCancelDuringDecompress(t *testing.T) {
	apk := buildApkTarGz(t, pkginfoText)
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	_, err := readPkgInfoFromPackage(ctx, bytes.NewReader(apk))
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("ожидали context.Canceled, получили %v", err)
	}
}

// gateReader отменяет ctx один раз после доставки gate байт и считает
// отданное: cancel-барьер в середине tar-потока. После отмены байты
// продолжают отдаваться — если код читает поток дальше, счётчик served
// это покажет.
type gateReader struct {
	r      io.Reader
	gate   int64
	served int64
	cancel context.CancelFunc
	fired  bool
}

func (g *gateReader) Read(p []byte) (int, error) {
	n, err := g.r.Read(p)
	g.served += int64(n)
	if !g.fired && g.served >= g.gate {
		g.fired = true
		g.cancel()
	}
	return n, err
}

// TestReadPkgInfoCancelMidStream — mid-stream вариант cancel-теста:
// отмена ДО вызова не отличает «ctx на каждом члене» от «ctx на входе»
// (верификация Р6). Несжатый tar с тремя членами (два заполнителя,
// .PKGINFO последним); gate-ридер отменяет ctx сразу после доставки
// первого члена (его заголовок — ровно 512 байт). Контракт: Canceled,
// а не успешный разбор — при «проверке на входе» .PKGINFO третьего
// члена был бы найден без ошибки; счётчик gate-ридера доказывает, что
// члены после отмены не доставлялись.
func TestReadPkgInfoCancelMidStream(t *testing.T) {
	var buf bytes.Buffer
	tw := tar.NewWriter(&buf)
	for _, name := range []string{"usr/bin/a", "usr/bin/b", ".PKGINFO"} {
		var content []byte
		if name == ".PKGINFO" {
			content = []byte(pkginfoText)
		}
		if err := tw.WriteHeader(&tar.Header{Name: name, Typeflag: tar.TypeReg, Mode: 0o644, Size: int64(len(content))}); err != nil {
			t.Fatalf("WriteHeader %s: %v", name, err)
		}
		if len(content) > 0 {
			if _, err := tw.Write(content); err != nil {
				t.Fatalf("Write .PKGINFO: %v", err)
			}
		}
	}
	if err := tw.Close(); err != nil {
		t.Fatalf("tw.Close: %v", err)
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	g := &gateReader{r: bytes.NewReader(buf.Bytes()), gate: 512, cancel: cancel}
	_, err := readPkgInfoFromTar(ctx, g)
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("ожидали context.Canceled, получили %v", err)
	}
	if g.served > 512 {
		t.Errorf("доставлено %d байт — члены после первого не должны читаться", g.served)
	}
}
