// Хражевник — кеш-прокси и зеркало linux-репозиториев
// Copyright (C) 2026 AlexRus1234
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

package pacman

import (
	"archive/tar"
	"bytes"
	"context"
	"crypto/sha256"
	"errors"
	"fmt"
	"io"
	"iter"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/klauspost/compress/zstd"

	"khrazhevnik/internal/core/domain"
	"khrazhevnik/internal/core/port"
	"khrazhevnik/internal/testutil"
)

// buildPkgTarZst собирает .pkg.tar.zst: zstd-сжатый tar с .PKGINFO
// (+ один data-файл для реалистичности). Генератор .PKGINFO не обязан
// быть первым членом, но repo-add кладёт его первым — делаем так же.
func buildPkgTarZst(t *testing.T, pkginfo string) []byte {
	t.Helper()
	var tarBuf bytes.Buffer
	tw := tar.NewWriter(&tarBuf)
	content := []byte(pkginfo)
	if err := tw.WriteHeader(&tar.Header{
		Name: ".PKGINFO", Typeflag: tar.TypeReg, Mode: 0o644, Size: int64(len(content)),
	}); err != nil {
		t.Fatal(err)
	}
	if _, err := tw.Write(content); err != nil {
		t.Fatal(err)
	}
	// data-файл (пустой) — реалистичность tar'а.
	if err := tw.WriteHeader(&tar.Header{
		Name: "usr/bin/foo", Typeflag: tar.TypeReg, Mode: 0o755, Size: 0,
	}); err != nil {
		t.Fatal(err)
	}
	if err := tw.Close(); err != nil {
		t.Fatal(err)
	}
	var zstBuf bytes.Buffer
	zw, err := zstd.NewWriter(&zstBuf)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := zw.Write(tarBuf.Bytes()); err != nil {
		t.Fatal(err)
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
	return zstBuf.Bytes()
}

// pkginfoText — типовой .PKGINFO для фикстур.
const pkginfoText = `# Generated by makepkg
pkgname = pacman-example
pkgver = 1.0-1
pkgdesc = Example package for tests
url = https://example.com
builddate = 1724323200
packager = Test Packager <test@example.com>
size = 2048
arch = x86_64
license = MIT
`

func TestParsePkgInfoGolden(t *testing.T) {
	pi, err := ParsePkgInfo(strings.NewReader(pkginfoText))
	if err != nil {
		t.Fatalf("ParsePkgInfo: %v", err)
	}
	if pi.Name != "pacman-example" {
		t.Errorf("Name = %q", pi.Name)
	}
	if pi.Version != "1.0-1" {
		t.Errorf("Version = %q", pi.Version)
	}
	if pi.Desc != "Example package for tests" {
		t.Errorf("Desc = %q", pi.Desc)
	}
	if pi.URL != "https://example.com" {
		t.Errorf("URL = %q", pi.URL)
	}
	if pi.Arch != "x86_64" {
		t.Errorf("Arch = %q", pi.Arch)
	}
	if pi.Size != 2048 {
		t.Errorf("Size = %d", pi.Size)
	}
	if pi.BuildDate != 1724323200 {
		t.Errorf("BuildDate = %d", pi.BuildDate)
	}
	if len(pi.License) != 1 || pi.License[0] != "MIT" {
		t.Errorf("License = %+v", pi.License)
	}
}

func TestParsePkgInfoMultiLicense(t *testing.T) {
	// license повторяется — все значения собираются.
	pi, err := ParsePkgInfo(strings.NewReader(
		"pkgname = foo\nlicense = MIT\nlicense = GPL-2.0\n"))
	if err != nil {
		t.Fatal(err)
	}
	if len(pi.License) != 2 || pi.License[0] != "MIT" || pi.License[1] != "GPL-2.0" {
		t.Errorf("License = %+v", pi.License)
	}
}

func TestParsePkgInfoCommentsAndCRLF(t *testing.T) {
	pi, err := ParsePkgInfo(strings.NewReader(
		"# comment\r\npkgname = foo\r\n\r\npkgver = 1.0\r\n"))
	if err != nil {
		t.Fatal(err)
	}
	if pi.Name != "foo" || pi.Version != "1.0" {
		t.Errorf("Name=%q Version=%q (CRLF/comments)", pi.Name, pi.Version)
	}
}

func TestParsePkgInfoUnknownKeyIgnored(t *testing.T) {
	pi, err := ParsePkgInfo(strings.NewReader(
		"futurefield = x\npkgname = foo\n"))
	if err != nil {
		t.Fatal(err)
	}
	if pi.Name != "foo" {
		t.Errorf("Name = %q", pi.Name)
	}
}

func TestParsePkgInfoNoEquals(t *testing.T) {
	// строки без «=» — tolerant, не ломают.
	pi, err := ParsePkgInfo(strings.NewReader("just text\npkgname = bar\n"))
	if err != nil {
		t.Fatal(err)
	}
	if pi.Name != "bar" {
		t.Errorf("Name = %q", pi.Name)
	}
}

func TestParsePkgInfoBadNumber(t *testing.T) {
	pi, err := ParsePkgInfo(strings.NewReader("size = not-a-number\nbuilddate = 5\n"))
	if err != nil {
		t.Fatal(err)
	}
	if pi.Size != 0 {
		t.Errorf("Size = %d, хочу 0 (битое)", pi.Size)
	}
	if pi.BuildDate != 5 {
		t.Errorf("BuildDate = %d", pi.BuildDate)
	}
}

func TestParsePkgInfoTooLarge(t *testing.T) {
	big := strings.Repeat("a", maxPkgInfoSize+1)
	_, err := ParsePkgInfo(strings.NewReader(big))
	if !errors.Is(err, ErrPkgInfoTooLarge) {
		t.Fatalf("ожидалась ErrPkgInfoTooLarge, получено %v", err)
	}
}

func TestParsePkgInfoDeterminism(t *testing.T) {
	first, ferr := ParsePkgInfo(strings.NewReader(pkginfoText))
	second, serr := ParsePkgInfo(strings.NewReader(pkginfoText))
	if !sameErr(ferr, serr) {
		t.Fatalf("недетерминированная ошибка")
	}
	if first.Name != second.Name || first.Version != second.Version {
		t.Fatal("недетерминированный разбор")
	}
}

func TestReadPkgInfoFromPackage(t *testing.T) {
	pkg := buildPkgTarZst(t, pkginfoText)
	pi, err := readPkgInfoFromPackage(context.Background(), bytes.NewReader(pkg))
	if err != nil {
		t.Fatalf("readPkgInfoFromPackage: %v", err)
	}
	if pi.Name != "pacman-example" || pi.Version != "1.0-1" {
		t.Errorf("Name=%q Version=%q", pi.Name, pi.Version)
	}
}

func TestReadPkgInfoFromTarMissing(t *testing.T) {
	// tar без .PKGINFO → ошибка.
	var tarBuf bytes.Buffer
	tw := tar.NewWriter(&tarBuf)
	_ = tw.WriteHeader(&tar.Header{Name: "usr/bin/foo", Typeflag: tar.TypeReg, Mode: 0o755, Size: 0})
	_ = tw.Close()
	_, err := readPkgInfoFromTar(context.Background(), bytes.NewReader(tarBuf.Bytes()))
	if err == nil || !strings.Contains(err.Error(), ".PKGINFO") {
		t.Fatalf("ожидали ошибку отсутствия .PKGINFO, got %v", err)
	}
}

func TestGeneratorName(t *testing.T) {
	g := &Generator{}
	if g.Name() != Name {
		t.Errorf("Name = %q, want %q", g.Name(), Name)
	}
}

func TestValidateObjectPath(t *testing.T) {
	g := &Generator{}
	cases := []struct {
		path string
		want bool
	}{
		{"foo-1.0-1-x86_64.pkg.tar.zst", true},
		{"foo-1.0-1-x86_64.pkg.tar.xz", false},
		{"foo-1.0-1-any.pkg.tar.gz", false},
		{"alice.db", false},
		{"alice.db.sig", false},
		{"foo.txt", false},
		{"", false},
	}
	for _, c := range cases {
		err := g.ValidateObjectPath(c.path)
		got := err == nil
		if got != c.want {
			t.Errorf("ValidateObjectPath(%q) = %v, want ok=%v", c.path, err, c.want)
		}
	}
}

// TestValidateObjectPathLegacyReason — legacy .xz/.gz отвергаются
// ValidationError с внятной причиной (маппится в 400): клиент должен
// понять, что пакет надо переупаковать, а не гадать, почему «неизвестное
// расширение». Один загруженный legacy-пакет без этого фильтра валил бы
// GenerateIndexes целиком (парсер читает .PKGINFO только через zstd).
func TestValidateObjectPathLegacyReason(t *testing.T) {
	g := &Generator{}
	for _, p := range []string{"foo-1.0-1-x86_64.pkg.tar.xz", "foo-1.0-1-any.pkg.tar.gz"} {
		var ve *domain.ValidationError
		err := g.ValidateObjectPath(p)
		if !errors.As(err, &ve) {
			t.Fatalf("ValidateObjectPath(%q): хочу ValidationError, получено %v", p, err)
		}
		if !strings.Contains(ve.Reason, "xz/gz не поддерживается") {
			t.Errorf("ValidateObjectPath(%q): причина без «xz/gz»: %q", p, ve.Reason)
		}
	}
	if err := g.ValidateObjectPath("foo-1.0-1-x86_64.pkg.tar.zst"); err != nil {
		t.Errorf("валидный .pkg.tar.zst отклонён: %v", err)
	}
}

// putPkg складывает .pkg.tar.zst-байты в FakeStorage.
func putPkg(t *testing.T, storage *testutil.FakeStorage, repo domain.Repo, name, pkginfo string) string {
	t.Helper()
	pkg := buildPkgTarZst(t, pkginfo)
	key := port.RepoPrefix(repo) + "/" + name
	w, err := storage.Put(context.Background(), key)
	if err != nil {
		t.Fatalf("storage.Put %s: %v", key, err)
	}
	if _, err := w.Write(pkg); err != nil {
		t.Fatalf("w.Write %s: %v", key, err)
	}
	if err := w.Commit(context.Background()); err != nil {
		t.Fatalf("w.Commit %s: %v", key, err)
	}
	return key
}

func readStorage(t *testing.T, storage *testutil.FakeStorage, key string) []byte {
	t.Helper()
	obj, err := storage.Get(context.Background(), key)
	if err != nil {
		t.Fatalf("Get %s: %v", key, err)
	}
	defer obj.Body.Close()
	b, err := io.ReadAll(obj.Body)
	if err != nil {
		t.Fatalf("ReadAll %s: %v", key, err)
	}
	return b
}

func TestGenerateIndexesSinglePkg(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putPkg(t, storage, repo, "pacman-example-1.0-1-x86_64.pkg.tar.zst", pkginfoText)

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}

	// alice.db существует; распаковываем zstd → tar → находим desc.
	db := readStorage(t, storage, "repo/1/pacman/alice.db")
	zr, err := zstd.NewReader(bytes.NewReader(db))
	if err != nil {
		t.Fatalf("zstd.NewReader: %v", err)
	}
	desc, err := findDescInTar(zr, "pacman-example-1.0-1-x86_64/desc")
	if err != nil {
		t.Fatalf("findDescInTar: %v", err)
	}
	for _, want := range []string{
		"%FILENAME%\npacman-example-1.0-1-x86_64.pkg.tar.zst\n",
		"%NAME%\npacman-example\n",
		"%VERSION%\n1.0-1\n",
		"%ARCH%\nx86_64\n",
		"%CSIZE%",
		"%SHA256SUM%",
	} {
		if !strings.Contains(desc, want) {
			t.Errorf("desc не содержит %q:\n%s", want, desc)
		}
	}
}

// findDescInTar ищет <dir>/desc в tar-потоке и возвращает его содержимое.
func findDescInTar(r io.Reader, want string) (string, error) {
	tr := tar.NewReader(r)
	for {
		hdr, err := tr.Next()
		if err != nil {
			return "", err
		}
		if hdr.Name == want {
			b, _ := io.ReadAll(tr)
			return string(b), nil
		}
	}
}

// roundtrip: список .pkg.tar.zst → .db → ParseDB → те же filenames.
func TestGenerateIndexesRoundtrip(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putPkg(t, storage, repo, "bar-2.3-4-aarch64.pkg.tar.zst",
		"pkgname = bar\npkgver = 2.3-4\narch = aarch64\n")
	putPkg(t, storage, repo, "foo-1.0-1-x86_64.pkg.tar.zst",
		"pkgname = foo\npkgver = 1.0-1\narch = x86_64\n")

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}

	db := readStorage(t, storage, "repo/1/pacman/alice.db")
	// ParseDB сам разжимает zstd; передаём сырые байты .db.
	entries, err := collectDB(ParseDB(bytes.NewReader(db)))
	if err != nil {
		t.Fatalf("ParseDB roundtrip: %v", err)
	}
	filenames := map[string]bool{}
	for _, e := range entries {
		filenames[e.Filename] = true
	}
	want := []string{"bar-2.3-4-aarch64.pkg.tar.zst", "foo-1.0-1-x86_64.pkg.tar.zst"}
	for _, w := range want {
		if !filenames[w] {
			t.Errorf("filename %q отсутствует в .db (roundtrip): %+v", w, filenames)
		}
	}
	// %SHA256SUM% в desc должен совпадать с sha256 файла .pkg.tar.zst.
	pkg := readStorage(t, storage, "repo/1/pacman/foo-1.0-1-x86_64.pkg.tar.zst")
	wantSha := fmt.Sprintf("%x", sha256.Sum256(pkg))
	// для sha-проверки desc распаковываем zstd → tar (findDescInTar на
	// разжатом tar-потоке).
	zr2, _ := zstd.NewReader(bytes.NewReader(db))
	desc, err := findDescInTar(zr2, "foo-1.0-1-x86_64/desc")
	if err != nil {
		t.Fatalf("findDesc foo: %v", err)
	}
	if !strings.Contains(desc, wantSha) {
		t.Errorf("desc foo не содержит sha256 %s файла", wantSha)
	}
}

func TestGenerateIndexesEmptyRepo(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes пустой репо: %v", err)
	}
	db := readStorage(t, storage, "repo/1/pacman/alice.db")
	// пустой tar.zst: ParseDB разжимает zstd, tar без записей → 0 desc.
	entries, _ := collectDB(ParseDB(bytes.NewReader(db)))
	if len(entries) != 0 {
		t.Errorf("пустой репо дал %d desc, хочу 0", len(entries))
	}
}

func TestGenerateIndexesWrongEcosystem(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: "apt"}
	g := &Generator{}
	err := g.GenerateIndexes(context.Background(), repo, storage, nil)
	var unsup *domain.UnsupportedError
	if !errors.As(err, &unsup) {
		t.Fatalf("ожидали UnsupportedError, получили %v", err)
	}
}

func TestGenerateIndexesContextCanceled(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putPkg(t, storage, repo, "foo-1.0-1-x86_64.pkg.tar.zst", pkginfoText)
	g := &Generator{}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if err := g.GenerateIndexes(ctx, repo, storage, nil); err == nil {
		t.Fatal("ожидали ошибку отменённого контекста")
	}
}

// recordingProgress ловит кадры Update.
type recordingProgress struct {
	updates []string
	logs    []string
}

func (r *recordingProgress) Update(phase, current string, processed, total int64) {
	r.updates = append(r.updates, fmt.Sprintf("%s/%s/%d/%d", phase, current, processed, total))
}
func (r *recordingProgress) Log(line string) { r.logs = append(r.logs, line) }

func TestGenerateIndexesProgress(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putPkg(t, storage, repo, "foo-1.0-1-x86_64.pkg.tar.zst", pkginfoText)
	g := &Generator{}
	rec := &recordingProgress{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, rec); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}
	phases := map[string]bool{}
	for _, u := range rec.updates {
		phases[strings.SplitN(u, "/", 2)[0]] = true
	}
	for _, want := range []string{"enumerate", "pkginfo", "write"} {
		if !phases[want] {
			t.Errorf("фаза %s не отработала: %v", want, rec.updates)
		}
	}
	if !slices.ContainsFunc(rec.logs, func(s string) bool { return strings.Contains(s, "индексы записаны") }) {
		t.Errorf("нет строки завершения: %v", rec.logs)
	}
}

// fakeSigner — port.Signer с детерминированным маркером.
type fakeSigner struct{}

func (fakeSigner) Sign(_ context.Context, _ io.Reader) (io.Reader, error) {
	return bytes.NewReader([]byte("cleartext-stub")), nil
}
func (fakeSigner) SignDetached(_ context.Context, _ io.Reader) (io.Reader, error) {
	return bytes.NewReader([]byte("detached-stub")), nil
}
func (fakeSigner) PublicKey() ([]byte, error) { return []byte("pub-stub"), nil }

func TestGenerateIndexesUnsignedNoSig(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putPkg(t, storage, repo, "foo-1.0-1-x86_64.pkg.tar.zst", pkginfoText)
	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}
	if _, err := storage.Get(context.Background(), "repo/1/pacman/alice.db.sig"); err == nil {
		t.Error("без Signer создан alice.db.sig")
	}
}

func TestGenerateIndexesSignedWritesSig(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putPkg(t, storage, repo, "foo-1.0-1-x86_64.pkg.tar.zst", pkginfoText)
	g := &Generator{signer: fakeSigner{}}
	rec := &recordingProgress{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, rec); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}
	sig := readStorage(t, storage, "repo/1/pacman/alice.db.sig")
	if string(sig) != "detached-stub" {
		t.Errorf("alice.db.sig = %q, хочу detached-stub", sig)
	}
	phases := map[string]bool{}
	for _, u := range rec.updates {
		phases[strings.SplitN(u, "/", 2)[0]] = true
	}
	if !phases["sign"] {
		t.Errorf("фаза sign не отработала: %v", rec.updates)
	}
}

// errSignFail — синтетическая ошибка подписчика.
var errSignFail = errors.New("synthetic signer failure")

type failSigner struct{}

func (failSigner) Sign(context.Context, io.Reader) (io.Reader, error) { return nil, errSignFail }
func (failSigner) SignDetached(context.Context, io.Reader) (io.Reader, error) {
	return nil, errSignFail
}
func (failSigner) PublicKey() ([]byte, error) { return nil, nil }

func TestGenerateIndexesSignedSignerErrorFails(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putPkg(t, storage, repo, "foo-1.0-1-x86_64.pkg.tar.zst", pkginfoText)
	g := &Generator{signer: failSigner{}}
	err := g.GenerateIndexes(context.Background(), repo, storage, nil)
	if !errors.Is(err, errSignFail) {
		t.Fatalf("ожидали errSignFail, got %v", err)
	}
}

func TestSetSigner(t *testing.T) {
	g := &Generator{}
	if g.signer != nil {
		t.Fatal("новый Generator уже имеет signer")
	}
	s := fakeSigner{}
	g.SetSigner(s)
	if g.signer == nil {
		t.Error("SetSigner не сохранил signer")
	}
}

// errListFail — синтетический сбой листинга носителя (см. Storage.List
// контракт: терминальная ошибка вместо пустого обхода).
var errListFail = errors.New("synthetic listing failure")

// failingListStorage — FakeStorage с отказом List: Get/Put честные,
// перечисление падает. Проверяет fail-closed генератора изолированно
// от носителя.
type failingListStorage struct {
	*testutil.FakeStorage
	err error
}

func (f *failingListStorage) List(_ context.Context, _ string) iter.Seq2[port.Meta, error] {
	return func(yield func(port.Meta, error) bool) {
		yield(port.Meta{}, f.err)
	}
}

// TestGenerateIndexesListingErrorKeepsOldIndexes — при ошибке листинга
// генерация падает, прежний .db остаётся байт-в-байт (fail-closed:
// транзиентный сбой носителя не «опустошает» репо).
func TestGenerateIndexesListingErrorKeepsOldIndexes(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putPkg(t, storage, repo, "foo-1.0-1-x86_64.pkg.tar.zst", pkginfoText)

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("первая генерация: %v", err)
	}
	const dbKey = "repo/1/pacman/alice.db"
	before := readStorage(t, storage, dbKey)

	broken := &failingListStorage{FakeStorage: storage, err: errListFail}
	err := g.GenerateIndexes(context.Background(), repo, broken, nil)
	if err == nil || !errors.Is(err, errListFail) {
		t.Fatalf("ожидали errListFail из листинга, получено %v", err)
	}
	after := readStorage(t, storage, dbKey)
	if !bytes.Equal(before, after) {
		t.Fatal("ошибка листинга перезаписала валидный .db (не fail-closed)")
	}
}

// TestGenerateIndexesDependencies — зависимости из .PKGINFO попадают в
// desc-запись .db (%DEPENDS%/%PROVIDES%/%CONFLICTS%, по значению на
// строку, как repo-add): без них `pacman -S` не резолвит зависимости
// из личного репо.
func TestGenerateIndexesDependencies(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	pkginfo := "pkgname = foo\npkgver = 1.0-1\narch = x86_64\n" +
		"depend = glibc\n" +
		"depend = libfoo>=2.0\n" +
		"provides = foo=1.0-1\n" +
		"conflict = foo-git\n"
	putPkg(t, storage, repo, "foo-1.0-1-x86_64.pkg.tar.zst", pkginfo)

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}

	// Распаковываем .db (zstd → tar) и читаем desc.
	dbBytes := readStorage(t, storage, "repo/1/pacman/alice.db")
	desc, err := extractDescFromDB(dbBytes, "foo-1.0-1-x86_64")
	if err != nil {
		t.Fatalf("extractDescFromDB: %v", err)
	}
	for _, want := range []string{
		"%DEPENDS%\nglibc\nlibfoo>=2.0\n\n",
		"%PROVIDES%\nfoo=1.0-1\n\n",
		"%CONFLICTS%\nfoo-git\n\n",
	} {
		if !strings.Contains(desc, want) {
			t.Errorf("desc не содержит %q:\n%s", want, desc)
		}
	}
}

// TestGenerateIndexesNoDependenciesOmitsFields — без depend/provides/
// conflict поля %DEPENDS%/%PROVIDES%/%CONFLICTS% не эмитятся.
func TestGenerateIndexesNoDependenciesOmitsFields(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	putPkg(t, storage, repo, "foo-1.0-1-x86_64.pkg.tar.zst", pkginfoText)

	g := &Generator{}
	if err := g.GenerateIndexes(context.Background(), repo, storage, nil); err != nil {
		t.Fatalf("GenerateIndexes: %v", err)
	}
	dbBytes := readStorage(t, storage, "repo/1/pacman/alice.db")
	desc, err := extractDescFromDB(dbBytes, "pacman-example-1.0-1-x86_64")
	if err != nil {
		t.Fatalf("extractDescFromDB: %v", err)
	}
	for _, banned := range []string{"%DEPENDS%", "%PROVIDES%", "%CONFLICTS%"} {
		if strings.Contains(desc, banned) {
			t.Errorf("desc содержит %q без зависимостей в пакете:\n%s", banned, desc)
		}
	}
}

// extractDescFromDB распаковывает .db (zstd+tar) и возвращает текст
// desc-файла каталога dir.
func extractDescFromDB(dbBytes []byte, dir string) (string, error) {
	zr, err := zstd.NewReader(bytes.NewReader(dbBytes))
	if err != nil {
		return "", err
	}
	defer zr.Close()
	tr := tar.NewReader(zr)
	for {
		hdr, err := tr.Next()
		if errors.Is(err, io.EOF) {
			return "", fmt.Errorf("каталог %s не найден в .db", dir)
		}
		if err != nil {
			return "", err
		}
		if strings.TrimPrefix(hdr.Name, "./") == dir+"/desc" {
			b, err := io.ReadAll(tr)
			if err != nil {
				return "", err
			}
			return string(b), nil
		}
	}
}

// pkgBombZst строит .pkg.tar.zst-бомбу: tar с одним членом объявленного
// размера huge, набитым повторами (сжимается в килобайты, разжимается
// больше капа). Запись потоковая через компрессор — память теста
// ограничена буфером, а не размером бомбы (по образцу apt controlBombGz).
func pkgBombZst(t *testing.T, huge int64) []byte {
	t.Helper()
	var raw bytes.Buffer
	zw, err := zstd.NewWriter(&raw, zstd.WithEncoderLevel(zstd.SpeedFastest))
	if err != nil {
		t.Fatalf("zstd.NewWriter: %v", err)
	}
	tw := tar.NewWriter(zw)
	if err := tw.WriteHeader(&tar.Header{Name: "bomb", Mode: 0o644, Size: huge, Typeflag: tar.TypeReg}); err != nil {
		t.Fatalf("tw.WriteHeader: %v", err)
	}
	chunk := bytes.Repeat([]byte{'A'}, 64<<10)
	var written int64
	for written+int64(len(chunk)) <= huge {
		if _, err := tw.Write(chunk); err != nil {
			t.Fatalf("tw.Write: %v", err)
		}
		written += int64(len(chunk))
	}
	if rest := huge - written; rest > 0 {
		if _, err := tw.Write(bytes.Repeat([]byte{'A'}, int(rest))); err != nil {
			t.Fatalf("tw.Write rest: %v", err)
		}
	}
	if err := tw.Close(); err != nil {
		t.Fatalf("tw.Close: %v", err)
	}
	if err := zw.Close(); err != nil {
		t.Fatalf("zw.Close: %v", err)
	}
	return raw.Bytes()
}

// TestReadPkgInfoDecompressBomb — внешний ревью, раунд 5: reindex-путь
// декомпрессии без капа (Enumerate каплен, генератор нет). Бомба
// (разжатых > maxDecompressed) — ErrDecompressTooLarge за лимитом,
// а не OOM. Счётчик лимитера доказывает отказ в процессе чтения:
// zstd-декодер отдаёт блоками с упреждением (замер на apt: ~0.9 МиБ за
// капом), поэтому точный «кап+δ» не ассертим — ассертим «бомба не
// дочитана». Плюс полный путь readPkgInfoFromPackage на той же бомбе.
func TestReadPkgInfoDecompressBomb(t *testing.T) {
	const huge = maxDecompressed + (1 << 20) // 1 GiB + 1 MiB
	bomb := pkgBombZst(t, huge)

	dr, err := decompressPkg(bytes.NewReader(bomb))
	if err != nil {
		t.Fatalf("decompressPkg: %v", err)
	}
	lr, ok := dr.(*limitedReadCloser)
	if !ok {
		t.Fatalf("decompressPkg вернул %T, хочу *limitedReadCloser", dr)
	}
	if _, err := io.ReadAll(dr); !errors.Is(err, ErrDecompressTooLarge) {
		t.Fatalf("ожидали ErrDecompressTooLarge на чтении, получили %v", err)
	}
	if lr.n >= huge {
		t.Errorf("разжато %d из %d байт — отказ обязан наступить до конца бомбы", lr.n, huge)
	}
	if err := dr.Close(); err != nil {
		t.Fatalf("dr.Close: %v", err)
	}

	if _, err := readPkgInfoFromPackage(context.Background(), bytes.NewReader(bomb)); !errors.Is(err, ErrDecompressTooLarge) {
		t.Fatalf("readPkgInfoFromPackage: ожидали ErrDecompressTooLarge, получили %v", err)
	}
}

// TestGenerateIndexesPkgBomb — reindex с бомбой-пакетом: задача failed
// с ошибкой декомпресс-лимита, индексы не закоммичены (пишутся только
// после успешного прохода всех пакетов).
func TestGenerateIndexesPkgBomb(t *testing.T) {
	moment := time.Date(2026, 8, 24, 12, 0, 0, 0, time.UTC)
	storage := testutil.NewFakeStorage(testutil.FixedClock(moment))
	repo := domain.Repo{ID: 1, Name: "alice", Ecosystem: Name}
	bomb := pkgBombZst(t, maxDecompressed+(1<<20))
	key := port.RepoPrefix(repo) + "/bomb-1.0-1-x86_64.pkg.tar.zst"
	w, err := storage.Put(context.Background(), key)
	if err != nil {
		t.Fatalf("storage.Put %s: %v", key, err)
	}
	if _, err := w.Write(bomb); err != nil {
		t.Fatalf("w.Write: %v", err)
	}
	if err := w.Commit(context.Background()); err != nil {
		t.Fatalf("w.Commit: %v", err)
	}

	err = (&Generator{}).GenerateIndexes(context.Background(), repo, storage, nil)
	if !errors.Is(err, ErrDecompressTooLarge) {
		t.Fatalf("ожидали ErrDecompressTooLarge, получили %v", err)
	}
	if _, err := storage.Get(context.Background(), "repo/1/pacman/alice.db"); err == nil {
		t.Error("индекс не должен быть закоммичен")
	}
}

// TestReadPkgInfoCancelDuringDecompress — отмена reindex-задачи гасит
// декомпрессию: ctx.Err() проверяется на каждом члене tar-потока, а не
// только между пакетами (раунд 5). Честный пакет с отменённым контекстом
// отказывается до первого tr.Next.
func TestReadPkgInfoCancelDuringDecompress(t *testing.T) {
	pkg := buildPkgTarZst(t, pkginfoText)
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	_, err := readPkgInfoFromPackage(ctx, bytes.NewReader(pkg))
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("ожидали context.Canceled, получили %v", err)
	}
}
